### ISSUE TITLE
tipdialog不消失的场景bug

### ISSUE THREAD

**Issue by HanGao1** [kongzue/DialogV3#10]
使用场景这样：你的demo一样必现bug~
先显示一个完成的Tipdialog，显示的时候马上按home键返回桌面，然后再点击app图标进入，此时dialog正常消失，然后按锁屏键，接着解锁，此时app仍然显示tipdialog，按返回键也不消失，求助

**Comment by kongzue** [comment]
请在主线程活动的情况下执行。此问题我会尝试修复

________________________________
发件人: HanGao1 <notifications@github.com>
发送时间: Wednesday, May 29, 2019 11:22:05 AM
收件人: kongzue/DialogV3
抄送: Subscribed
主题: [kongzue/DialogV3] tipdialog不消失的场景bug (#10)


使用场景这样：你的demo一样必现bug~
先显示一个完成的Tipdialog，显示的时候马上按home键返回桌面，然后再点击app图标进入，此时dialog正常消失，然后按锁屏键，接着解锁，此时app仍然显示tipdialog，按返回键也不消失，求助

―

**Comment by kongzue** [comment]
请更新至 3.0.2 版本已修复此问题。
