### ISSUE TITLE
WaitDialog无法关闭问题

### ISSUE THREAD

**Issue by JackyBower** [kongzue/DialogV3#101]
在同一个页面调用多次接口，而每次接口请求的时候WaitDialog提示语不同，如果第一个请求完一个接口要关闭WaitDialog吗？

**Comment by kongzue** [comment]
1.WaitDialog.show(...)方法会返回实例化对象，执行setMessage(...)方法可设置显示内容文本；
2.重复执行WaitDialog.show(...)可以不中断直接继续显示新的文本；
3.WaitDialog全局只有一个实例对象，请放心使用，任意地方执行WaitDialog.dismiss()都可直接关闭。

**Comment by KitTak** [comment]
WaitDialog.dismiss()无法关闭，目前就这个场景，查询完数据无法关闭

**Comment by kongzue** [comment]
您可以尝试运行Demo看是否能够正常关闭，如果可以，请检查您的代码是否存在导致其不能正常关闭的可能，如果也不行，请告诉我您的设备型号及系统版本，我将会找一台相同的设备进行测试。

**Comment by dyf505776897** [comment]
出现相同问题

**Comment by kongzue** [comment]
@dyf505776897 请尝试Demo是否正常运行
