### ISSUE TITLE
DialogHelper仍有内存泄漏

### ISSUE THREAD

**Issue by JingweiWang** [kongzue/DialogV3#102]
出现版本：v3.1.6

Known leak pattern: instance field android.os.Message#obj

2594818 bytes retained
┬
├─ android.os.HandlerThread
│    Leaking: UNKNOWN
│    Thread name: 'NetWorkSender'
│    GC Root: Java local variable
│    ↓ thread HandlerThread.<Java Local>
│                           ~~~~~~~~~~~~
├─ android.os.Message
│    Leaking: UNKNOWN
│    ↓ Message.obj
│              ~~~
╰→ com.kongzue.dialog.util.DialogHelper
​     Leaking: YES (Fragment#mFragmentManager is null and ObjectWatcher was watching this)
​     key = 634c31ee-ef9e-4e0a-b9f0-0f1079a601fa
​     watchDurationMillis = 2174538
​     retainedDurationMillis = 2169538
​     key = 05ca373b-4492-419e-8112-592594da8845
​     watchDurationMillis = 2174539

METADATA

Build.VERSION.SDK_INT: 28
Build.MANUFACTURER: Xiaomi
LeakCanary version: 2.0
Analysis duration: 17981 ms

**Comment by kongzue** [comment]
我无法确定您所给出的泄露的位置，目前所有DialogHelper引用均已加入WeakReference

**Comment by kongzue** [comment]
长时间未收到您的答复，暂时关闭此问题。如有疑问可继续回复。
