### ISSUE TITLE
在使用请求的时候 加入WaitDialog  出现内存泄漏问题

### ISSUE THREAD

**Issue by yinking1203** [kongzue/DialogV3#103]
![1](https://user-images.githubusercontent.com/23116465/70370166-b70c0700-18fe-11ea-889d-7af0383ca684.png)
使用清除语句  也还是直接崩溃

**Comment by kongzue** [comment]
请提供崩溃日志，否则我无法确认问题的位置

**Comment by yinking1203** [comment]
&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"notifications"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月7日(星期六) 下午2:47
收件人:&nbsp;"kongzue/DialogV3"<DialogV3@noreply.github.com&gt;;
抄送:&nbsp;"尹江峰"<526241452@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kongzue/DialogV3] 在使用请求的时候 加入WaitDialog  出现内存泄漏问题 (#103)




请提供崩溃日志，否则我无法确认问题的位置

**Comment by yinking1203** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"notifications"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月7日(星期六) 下午2:47
收件人:&nbsp;"kongzue/DialogV3"<DialogV3@noreply.github.com&gt;;
抄送:&nbsp;"尹江峰"<526241452@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kongzue/DialogV3] 在使用请求的时候 加入WaitDialog  出现内存泄漏问题 (#103)




请提供崩溃日志，否则我无法确认问题的位置

**Comment by yinking1203** [comment]
> 请提供崩溃日志，否则我无法确认问题的位置

![3](https://user-images.githubusercontent.com/23116465/70371443-263d2780-190e-11ea-9bc8-c2f56db46e3b.png)
 现在使用任何一个dialog  都会崩溃  用的是夜神模拟器   具体的报错  Channel is unrecoverably broken and will be disposed!  就这句 内存问题

**Comment by yinking1203** [comment]
Channel is unrecoverably broken and will be disposed!

**Comment by kongzue** [comment]
无法根据您的日志判断您所述的内存泄漏的问题。
因为DialogV3并未调用Channel，并且您所提供的日志无法表明DialogV3中存在的问题，请至少提供com.kongzue.dialog包名下的崩溃日志。

**Comment by yinking1203** [comment]
能否有个群交流或者是其他交流方式




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"notifications"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月7日(星期六) 下午4:30
收件人:&nbsp;"kongzue/DialogV3"<DialogV3@noreply.github.com&gt;;
抄送:&nbsp;"尹江峰"<526241452@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [kongzue/DialogV3] 在使用请求的时候 加入WaitDialog  出现内存泄漏问题 (#103)




无法根据您的日志判断您所述的内存泄漏的问题。
 因为DialogV3并未调用Channel，并且您所提供的日志无法表明DialogV3中存在的问题，请至少提供com.kongzue.dialog包名下的崩溃日志。

**Comment by kongzue** [comment]
我没有自己的群，但你可以加我同为管理员的技术交流群：271127803
