### ISSUE TITLE
WaitDialog无法设置颜色

### ISSUE THREAD

**Issue by ToMyBestLove** [kongzue/DialogV3#106]
内置的等待颜色为白色或者黑色
无法选择其它颜色

**Comment by kongzue** [comment]
等待动画本身没有设计可修改颜色的功能，如果需要使用，我会考虑在后续版本支持修改此组件颜色。

**Comment by Hn1993** [comment]
WaitDialog.show(MainActivity.this, "请稍候...").setMessageTextInfo(new TextInfo().setFontColor(getResources().getColor(R.color.color_orange)));   -- 使用

> 等待动画本身没有设计可修改颜色的功能，如果需要使用，我会考虑在后续版本支持修改此组件颜色。
> 若您是指背景颜色，目前没有计划提供修改颜色的选项，但您可以通过自定义背景图来实现：
> 
> ```
> DialogSettings.tipBackgroundResId = R.drawable.customBkg;
> ```
> 
> 额外的，若您是指文字颜色，可通过setMessageTextInfo(...)方法单独设置，或通过以下全局方法进行设置：
> 
> ```
> DialogSettings.tipTextInfo = customTextInfo;
> ```
> 
> 等待您的回复。

WaitDialog.show(MainActivity.this, "请稍候...").setMessageTextInfo(new TextInfo().setFontColor(getResources().getColor(R.color.color_orange)));
-- 使用此方法进行修改文字颜色不生效 测试机型 Pixel 3x

**Comment by kongzue** [comment]
@Hn1993 WaitDialog目前仅支持全局的DialogSettings.tipTextInfo 设置文字样式，目前不支持单独设置样式，因为WaitDialog实际上和TipDialog是共用的组件，且为保证“等待框”和“提示框”能够衔接，两组件中的显示模块也是共用的，因此不支持单独设置样式。

**Comment by kongzue** [comment]
已在 3.1.9.4 版本中对TipDialog和WaitDialog进行了修改，请使用setTipTextInfo(...)进行设置。
