### ISSUE TITLE
等待加载对话框

### ISSUE THREAD

**Issue by 79660095** [kongzue/DialogV3#109]
加载动画的时候 白色圈子旋转会出现一闪一闪的状况，V2Dialog版本不会，查看源码发现你两个版本引用的不是同一个ProgressBar。 然后就是建议这个加载最好可以提供两种风格  一种是旋转菊花 一种就是这种圈子的， 谢谢大佬。

**Comment by kongzue** [comment]
因为之前使用的ProgressBar组件存在后台后恢复就消失的bug，而系统的组件无法自定义粗细，且不支持颜色修改，此组件使用的是 https://github.com/cr1944/ProgressBar 的开源组件，等待其作者更新。

**Comment by kongzue** [comment]
由于长时间未回复，暂时关闭此问题，如有疑问可继续回复沟通
