### ISSUE TITLE
BottomMenu的底部取消按钮出不来 BottomMenu 列表过长的时候不能滑动

### ISSUE THREAD

**Issue by q232916067** [kongzue/DialogV3#11]
如题。

**Comment by q232916067** [comment]
//        BottomMenu.show((AppCompatActivity) mContext, list, new OnMenuItemClickListener() {
//            @Override
//            public void onClick(String text, int index) {
//                switch (index) {
//                    case 0:
//                        mPresenter.refreshList(null);
//                        break;
//                    case 1:
//                        mPresenter.refreshList(C.dealType.buy);
//                        break;
//                    case 2:
//                        mPresenter.refreshList(C.dealType.sell);
//                        break;
//                }
//
//            }
//        }).setCancelButtonText("取消").setShowCancelButton(true).show();
//        DialogSettings.DEBUGMODE = true;
//        DialogSettings.isUseBlur = true;
//        //DialogSettings.backgroundColor = Color.BLUE;
//        //DialogSettings.titleTextInfo = new TextInfo().setFontSize(50);
//        //DialogSettings.buttonPositiveTextInfo = new TextInfo().setFontColor(Color.GREEN);
//        DialogSettings.style = DialogSettings.STYLE.STYLE_IOS;
//        DialogSettings.theme = DialogSettings.THEME.LIGHT;

        BottomMenu.show((AppCompatActivity)mContext, new String[]{"菜单1", "菜单2", "菜单3"}, new OnMenuItemClickListener() {
            @Override
            public void onClick(String text, int index) {
            }
        });
下面的代码就可以 我上面的注释的代码就没有取消

**Comment by q232916067** [comment]
好吧 默认风格没有取消

**Comment by kongzue** [comment]
![image](https://user-images.githubusercontent.com/10115359/58615921-e8bc6980-82ee-11e9-8772-62df8b1f7012.png)

**Comment by kongzue** [comment]
其实布局上是有的，但Material风格本身就可以下滑关闭所以隐藏掉了
