### ISSUE TITLE
FullScreenDialog 可以弹出 activity/fragment 嘛

### ISSUE THREAD

**Issue by wangrui460** [kongzue/DialogV3#111]
FullScreenDialog 可以弹出 activity/fragment 嘛

**Comment by kongzue** [comment]
本组件库任何Dialog组件都是基于DialogFragment的实现，Activity是不可以插入DialogFragment的，如果你是指使用startActivity跳转，Android系统规定，在您的App处于活动状态的任意位置都可以使用context.startActivity(...)方法进行跳转。

**Comment by wangrui460** [comment]
那 可以弹出我写好的 fragment 吗

**Comment by kongzue** [comment]
根据Google定义，Fragment并不能单独“弹”出，Fragment是依赖于容器显示的，请确认您是否有准备显示Fragment的容器，并参照Fragment的显示操作文档来显示：
https://developer.android.google.cn/jetpack/androidx/releases/fragment

**Comment by wangrui460** [comment]
rootview 中加入 viewpager，viewpager显示想显示的fragment？

**Comment by kongzue** [comment]
ViewPager 作为 Fragment 的显示容器，是可以显示您的自定义 Fragment 的，请参照 ViewPager 的使用说明：
https://www.jianshu.com/p/9faa1fc3f527
在完成 ViewPager 中显示 Fragment 的代码后，您可以将 ViewPager 作为自定义布局加入到您的 Dialog 组件中，具体请参照相应组件的“自定义布局”章节：
https://github.com/kongzue/DialogV3#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%B8%83%E5%B1%80

**Comment by wangrui460** [comment]
因为你的Dialog组件都是基于DialogFragment的实现，而在fragment中使用fragmentManager都要用getChildFragmentManager，我在onBind方法中无法调用getChildFragmentManager，所以应该是没有办法实现了~

**Comment by kongzue** [comment]
目前 Google 已经不建议使用原始的 AlertDialog 做实现了，且为规避可能造成的 WindowLeaked 异常等问题，Kongzue Dialog 库已全部更新为使用 DialogFragment 作为实现体的组件，对此带来的不便尽请谅解。

**Comment by wangrui460** [comment]
mCustomDialog.dialog.get().getChildFragmentManager()

通过这种方式是可以拿到 getChildFragmentManager 的，所以我上面提出的那个猜想是可行的（rootview 中加入 viewpager，viewpager显示想显示的fragment？），已实践！

**Comment by kongzue** [comment]
因为你这种想法我没尝试过，但如果缺少什么接口或需要提供的功能尽管提给我，我都会尽快提供
