### ISSUE TITLE
自定义dialog，弹出两个dialog后，第一次dialog的背景色变透明了

### ISSUE THREAD

**Issue by wangrui460** [kongzue/DialogV3#113]
自定义dialog，弹出两个dialog后，第一次dialog的背景色变透明了，可否让第一个dialog的背景色不变啊~

**Comment by kongzue** [comment]
背景色是指？

**Comment by wangrui460** [comment]
就是弹框有一个默认的灰度背景

**Comment by wangrui460** [comment]
期望是这样的
<img width="388" alt="image" src="https://user-images.githubusercontent.com/11909313/71391691-35c3ac80-2640-11ea-9b72-526fb4044e55.png">

实现效果却是这样的
<img width="279" alt="image" src="https://user-images.githubusercontent.com/11909313/71391762-8cc98180-2640-11ea-9027-29a559d07fa2.png">

问题：
1.  背景遮罩问题
2. MessageDialog 不想要title，设置title=“”也不行
3. MessageDialog 感觉有点太透明了，后面的文字都能看清

**Comment by kongzue** [comment]
这个遮罩是系统DialogFragment默认自带的遮罩，如果出现问题建议从系统Dialog遮罩层入手查找问题
