### ISSUE TITLE
空指针

### ISSUE THREAD

**Issue by Andy957** [kongzue/DialogV3#116]
Attempt to invoke virtual method 'void com.kongzue.dialog.util.a.setStyle(int, int)' on a null object reference

com.kongzue.dialog.util.BaseDialog.n(BaseDialog.java:15)

**Comment by kongzue** [comment]
请尝试测试版本 3.1.7.1 是否能解决此问题，另外如果可以请勿提供混淆后的日志，具体混淆配置可参考https://github.com/kongzue/DialogV3#%E6%B7%B7%E6%B7%86%E8%AE%BE%E7%BD%AE

**Comment by Andy957** [comment]
ok，这个是bugly上面的
