### ISSUE TITLE
高德地图问题

### ISSUE THREAD

**Issue by baiyongchen** [kongzue/DialogV3#117]
楼主看看是不是跟高德地图有冲突呢？

**Comment by kongzue** [comment]
没冲突，因为我们有外包项目就在用高德地图，没见到有啥问题

**Comment by baiyongchen** [comment]
引入包。什么都不配置。直接运行。高德地图页面黑屏了。去掉你的引用是ok的

**Comment by kongzue** [comment]
这是我们某项目的配置，没有任何问题
![Snipaste_2019-12-24_19-44-57](https://user-images.githubusercontent.com/10115359/71411820-df795c80-2685-11ea-9d6f-0d9db89237fb.png)

**Comment by kongzue** [comment]
运行效果：
![CD89A557B08EC6CFB701F8984CAED11C](https://user-images.githubusercontent.com/10115359/71412020-a4c3f400-2686-11ea-8328-14e7736134f3.jpg)
![Snipaste_2019-12-24_19-44-57](https://user-images.githubusercontent.com/10115359/71412021-a55c8a80-2686-11ea-8844-f9a19359ec40.png)

**Comment by kongzue** [comment]
另外，DialogV3库的底层是由Google提供的DialogFragment，如果说高德地图有不兼容问题，那么应该是高德地图不兼容DialogFragment，那么应该提交高德方处理

**Comment by kongzue** [comment]
长时间未收到您的回复，先关闭此问题，如有疑问可继续回复
