### ISSUE TITLE
打包release开启混淆模糊效果开启无效,弹出的Dialog背景太透明能看见下面的内容

### ISSUE THREAD

**Issue by lijore** [kongzue/DialogV3#118]
Android版本9.0 现在手上的机型是联想Z6

**Comment by lijore** [comment]
该问题是因为RenderScript支持库未被混淆了

解决如下
-dontwarn android.support.v8.renderscript.**
-keep public class android.support.v8.renderscript.** { *; }

**Comment by kongzue** [comment]
奇怪的是，我这里有基于API-28的上线的项目在开启模糊效果和混淆的情况下，并未出现问题。
此问题已记录，并更新文档，在混淆设置中建议开启此keep
