### ISSUE TITLE
在4.4机型上出现not found

### ISSUE THREAD

**Issue by flyOfYW** [kongzue/DialogV3#119]
![D66656B7-DC7C-4AEF-9A0C-4E6CA692356B](https://user-images.githubusercontent.com/17938752/71638627-d436ba00-2c9f-11ea-91d2-d67dfa305fa7.png)
@kongzue

**Comment by kongzue** [comment]
设备不支持 renderscript 导致的，请使用以下语句关闭高斯模糊效果（renderscript）：
DialogSettings.isUseBlur = false;
下个版本将对此类增加判断。
