### ISSUE TITLE
为什么传入的context必须是AppCompatActivity类型的

### ISSUE THREAD

**Issue by qiushui95** [kongzue/DialogV3#12]
我在fragment内使用  只能拿到fragmentactivity，虽然也是AppCompatActivity类型的，但是每次都要强转一次，感觉很麻烦

**Comment by kongzue** [comment]
1.因为Google规定，Dialog必须依赖于Activity实现；
2.因为底层用了v4版的DialogFragment，以及一些必须AppCompatActivity实现的特性；
3.你不想转就得我转...而我懒得转......
大概就是这样......

**Comment by bingely** [comment]
不转成AppCompatActivity类型，直接用context强转，dissmiss 无效果

**Comment by Yanqilong** [comment]
@kongzue 如果在 Fragment 使用，需要将 getActivity 返回的 FragmentActivity 墙砖为 AppCompatActivity 对象，AppCompatActivity 是 FragmentActivity 子类，这样墙砖不合理。
你说需要依赖 Activity ，那为什么不用 Activity 作为参数对象，这样在 Fragment 中使用就不需要强转类型

**Comment by kongzue** [comment]
因为Google傻逼。
DialogFragment必须使用getSupportFragmentManager方法得到android.support.v4.app.FragmentManager，而此方法在AppCompatActivity里(准确说是AppCompatActivity的继承父类FragmentActivity，但他们都是Support包的限定类)，虽然非AppCompatActivity也可以用普通FragmentManager支持，但这牵扯太多代码修改，且无法使用android.support.v4.app.FragmentManager中提供的特有方法，这种混乱问题除非你能让Google对此做出修改。


________________________________
发件人: Yan qilong <notifications@github.com>
发送时间: Saturday, April 11, 2020 5:20:44 PM
收件人: kongzue/DialogV3 <DialogV3@noreply.github.com>
抄送: Kongzue <myzcxhh@live.cn>; Mention <mention@noreply.github.com>
主题: Re: [kongzue/DialogV3] 为什么传入的context必须是AppCompatActivity类型的 (#12)


@kongzue<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkongzue&data=02%7C01%7C%7C5b8b1293f8b24bddd05908d7ddf99e59%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637221936473575249&sdata=L3%2FH7FmR4jFIKunB3aJlmW3rQv8UMa%2FnlveKusjuzjc%3D&reserved=0> 如果在 Fragment 使用，需要将 getActivity 返回的 FragmentActivity 墙砖为 AppCompatActivity 对象，AppCompatActivity 是 FragmentActivity 子类，这样墙砖不合理。
你说需要依赖 Activity ，那为什么不用 Activity 作为参数对象，这样在 Fragment 中使用就不需要强转类型

―

**Comment by kongzue** [comment]
另外，Fragment本身就是绑定Activity来显示的，那么在一个AppCompatActivity中对getActivity做AppCompatActivity类型的强转我也不认为有任何问题，你要是强迫症受不了可以试试我的Baseframework框架，可以在任意地方使用关键词me代指Context，例如BaseFragment的实现类中的me自然直接指向其绑定的BaseActivity的实现类

________________________________
发件人: zhang chao <myzcxhh@live.cn>
发送时间: Saturday, April 11, 2020 5:28:49 PM
收件人: kongzue/DialogV3 <reply@reply.github.com>; kongzue/DialogV3 <DialogV3@noreply.github.com>
抄送: Mention <mention@noreply.github.com>
主题: Re: [kongzue/DialogV3] 为什么传入的context必须是AppCompatActivity类型的 (#12)

因为Google傻逼。
DialogFragment必须使用getSupportFragmentManager方法得到android.support.v4.app.FragmentManager，而此方法在AppCompatActivity里(准确说是AppCompatActivity的继承父类FragmentActivity，但他们都是Support包的限定类)，虽然非AppCompatActivity也可以用普通FragmentManager支持，但这牵扯太多代码修改，且无法使用android.support.v4.app.FragmentManager中提供的特有方法，这种混乱问题除非你能让Google对此做出修改。


________________________________
发件人: Yan qilong <notifications@github.com>
发送时间: Saturday, April 11, 2020 5:20:44 PM
收件人: kongzue/DialogV3 <DialogV3@noreply.github.com>
抄送: Kongzue <myzcxhh@live.cn>; Mention <mention@noreply.github.com>
主题: Re: [kongzue/DialogV3] 为什么传入的context必须是AppCompatActivity类型的 (#12)


@kongzue<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkongzue&data=02%7C01%7C%7C5b8b1293f8b24bddd05908d7ddf99e59%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637221936473575249&sdata=L3%2FH7FmR4jFIKunB3aJlmW3rQv8UMa%2FnlveKusjuzjc%3D&reserved=0> 如果在 Fragment 使用，需要将 getActivity 返回的 FragmentActivity 墙砖为 AppCompatActivity 对象，AppCompatActivity 是 FragmentActivity 子类，这样墙砖不合理。
你说需要依赖 Activity ，那为什么不用 Activity 作为参数对象，这样在 Fragment 中使用就不需要强转类型

―
