### ISSUE TITLE
没有设置isUseBlur，弹窗显示有半透明效果

### ISSUE THREAD

**Issue by summertravel** [kongzue/DialogV3#120]
![Screenshot_20200102_141631](https://user-images.githubusercontent.com/18628634/71654109-d4e85280-2d6a-11ea-89a0-8e05aa8c9144.jpg)

**Comment by summertravel** [comment]
备注：STYLE_IOS下显示此效果，STYLE_MATERIAL设置下无透明效果

**Comment by summertravel** [comment]
看了下源码，STYLE_IOS下，我需要设置isUseBlur=true，blurAlpha=255，才可以达到我的效果，请问还有别的处理方案么

**Comment by kongzue** [comment]
您好，此问题系原先设计就是按照90%作为背景的，我正在考虑修改这个样式为不透明。

**Comment by kongzue** [comment]
请更新至最新正式版已修改默认为不透明背景
