### ISSUE TITLE
DialogHelper 内存泄漏

### ISSUE THREAD

**Issue by shuigesuntao** [kongzue/DialogV3#122]
![WechatIMG2](https://user-images.githubusercontent.com/20171364/72143461-b7059800-33d1-11ea-8954-11030c9b668a.jpeg)

**Comment by kongzue** [comment]
请告知具体哪里有内存泄漏，我无法根据您的截图判断位置

**Comment by shuigesuntao** [comment]
DialogFragment的onCancelListener

**Comment by kongzue** [comment]
由于DialogFragment是系统组件，我无法对其进行修改，请将此问题报告给Google进行处理。

**Comment by moz1q1** [comment]
。。。

**Comment by moz1q1** [comment]
@Override
    public void onActivityCreated(@Nullable Bundle savedInstanceState) {
        super.onActivityCreated(savedInstanceState);
        if (getDialog() != null) {
            try {
                // 解决Dialog内D存泄漏
                getDialog().setOnDismissListener(null);
                getDialog().setOnCancelListener(null);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

**Comment by moz1q1** [comment]
https://www.jianshu.com/p/f2d6e6bc4b77

**Comment by kongzue** [comment]
我目前无法在用户的Activity中插入此行为，但您的反馈提供了一种可能，就是DialogFragment本身存在Listener回调泄露的问题，我会尝试修复此问题

**Comment by kongzue** [comment]
此问题已尝试按照你提供的方案处理，请等待下一版本更新
