### ISSUE TITLE
使用屏幕适配对话框不居中，跑到左上角了

### ISSUE THREAD

**Issue by feisher** [kongzue/DialogV3#124]
![device-2020-01-15-170211.png](https://i.loli.net/2020/01/15/qNe9aTj8nVYM6Hv.png)

**Comment by kongzue** [comment]
请根据以下方式排查：
1.请检查是否有使用“头条适配”之类的第三方适配工具；
2.是否有使用自定义style；
3.是否有尝试运行Demo看有没有问题；
另外请告知设备型号和系统版本，我这边会进行测试；

**Comment by feisher** [comment]
@kongzue 使用了“头条适配”改良版，重写了getResources方法。重点是设备是800x1280的终端，非手机，手机上是正常的

**Comment by kongzue** [comment]
目前DialogV3尚不支持其他适配形式，原生方式运行是没有问题的
