### ISSUE TITLE
崩溃 The specified child already has a parent. You must call removeView() on the child's parent first

### ISSUE THREAD

**Issue by wangrui460** [kongzue/DialogV3#127]
崩溃原因同 #96 
不同的是 96出现在WaitDialog中，而CustomDialog页存在这样的问题？

有没有临时解决的办法？？？挺急的

**Comment by kongzue** [comment]
您好，因疫情原因暂未复工，您的反馈已经收到，我会尽快处理。

**Comment by kongzue** [comment]
您好，经过查证，CustomDialog中对boxCustom已有相关处理，如果您可以提供指向具体行的崩溃日志我会进一步查证

**Comment by kongzue** [comment]
您好，长时间未收到您的回复，暂时先关闭此问题，如有疑问可继续回复
