### ISSUE TITLE
使用自定义CustomDialog构建时，使用CustomDialog.ALIGN.TOP，会导致布局显示不完全

### ISSUE THREAD

**Issue by underwes** [kongzue/DialogV3#128]
CustomDialog.build((AppCompatActivity) mContext, R.layout.menu_contrast, new CustomDialog.OnBindView() {
            @Override
            public void onBind(CustomDialog dialog, View v) {
                TextView contrastUntreated = v.findViewById(R.id.contrast_untreated);
                TextView contrastRecord = v.findViewById(R.id.contrast_record);
                contrastRecord.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                     
                        dialog.doDismiss();
                    }
                });
                contrastUntreated.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                    
                        dialog.doDismiss();
                    }
                });
            }
        }).setAlign(CustomDialog.ALIGN.TOP).setCancelable(true).show();

**Comment by underwes** [comment]
![image](https://user-images.githubusercontent.com/56291250/74898639-6ec89500-53d5-11ea-99db-5d55afa5b6a6.png)

**Comment by underwes** [comment]
截图部分是我自己修改的

**Comment by kongzue** [comment]
您好，这应该是由于自定义的原始布局宽高未定义导致的，设置为具体值即可

**Comment by underwes** [comment]
![image](https://user-images.githubusercontent.com/56291250/76202289-8efaaf80-622f-11ea-9193-e778eccd38fa.png)

**Comment by underwes** [comment]
是这个地方设置固定宽高吗

**Comment by kongzue** [comment]
对，具体可参考Demo
