### ISSUE TITLE
今日头条的屏幕适配方案能正确的适配 DialogV3吗

### ISSUE THREAD

**Issue by protectedMan** [kongzue/DialogV3#129]
https://github.com/JessYanCoding/AndroidAutoSize
我记得DialogV2版本在对这个库的兼容性上有问题，没法正确适配dialog上的字体。

**Comment by kongzue** [comment]
很抱歉，此问题需要今日头条解决。DialogV3库一直都是使用的默认原生的适配方式，如果使用其他适配方式需要自行修改。
