### ISSUE TITLE
tipdialog显示后不消失

### ISSUE THREAD

**Issue by HanGao1** [kongzue/DialogV3#13]
新版本出现新问题了，tipdialog显示了不自动消失

**Comment by kongzue** [comment]
3.0.2版本并没有发现此问题，在Pixel2、一加7Pro、坚果Pro、小米8上测试通过。
您可以尝试Demo看能否复现此问题。

**Comment by HanGao1** [comment]
我这边在小米8se android 自带模拟器均是同样的问题，我直接从3.0.1升级到的3.0.2，难道要clean?

**Comment by kongzue** [comment]
应该不需要，或者你把你显示TipDialog 的代码给我一份我这边跑一下测试看看

**Comment by HanGao1** [comment]
我这边再观察一下，项目是公司的。。

**Comment by zhangchaoxu** [comment]
@kongzue 同3.0.2，我在模拟器上，也出现了TipDialog不主动消失的问题。只是表现有点奇怪。
我在个人信息页面中有一个通过接口获取用户信息的功能，在进入和下拉刷新的时候，会调用，在接口出问题的时候会有tipdialog提示。
现在在进入的时候显示的tipdialog会主动消失，但是在下拉刷新时候的tipdialog不会主动消失

`TipDialog.show(activity, BoneException.getMsgByCode(errorCode), TipDialog.TYPE.ERROR).setCancelable(true);`

**Comment by HanGao1** [comment]
看来只能暂时不用tipdialog,clean项目后仍然不消失

**Comment by zhangchaoxu** [comment]
@HanGao1 可以尝试主动设置tiptime来解决问题
我现在的做法是
`TipDialog.show(activity,"errormsg", TipDialog.TYPE.ERROR)
                .setCancelable(true)
                .setTipTime(2000)`

**Comment by zhangchaoxu** [comment]
@kongzue 我推测是TipTime出了问题

**Comment by HanGao1** [comment]
@zhangchaoxu 好的感谢  我先测试一波

**Comment by kongzue** [comment]
![Video_20190531_105321_189](https://user-images.githubusercontent.com/10115359/58678458-6a190800-8392-11e9-8641-4e1a17aa6522.gif)
测试了一下您的代码 ，没有遇到此问题

**Comment by kongzue** [comment]
emmmm好吧，我测试成 @zhangchaoxu 的代码了...

**Comment by HanGao1** [comment]
@kongzue  你用模拟器试试  我的8se也不行的

**Comment by zhangchaoxu** [comment]
@kongzue 在一处逻辑中的tipdialog确实不会有问题的，我觉得这个问题可能是不同逻辑处的tipdialog相互影响引起的。
同样的这段代码，在有些地方会消失，有些地方不会消失

**Comment by kongzue** [comment]
稍等正在厕所

**Comment by kongzue** [comment]
找到原因了，这个应该是因为昨天修复切换后台导致dismiss事件执行失效问题结果又触发的另一个问题。感谢反馈，稍后我会更新一个版本。

**Comment by kongzue** [comment]
请更新至 3.0.3 版本，文档稍后更新

**Comment by zhangchaoxu** [comment]
👍，3.0.3测试正常

**Comment by kongzue** [comment]
> 👍，3.0.3测试正常

好的，如有任何问题可以随时联系我
