### ISSUE TITLE
关于androidx的一个问题

### ISSUE THREAD

**Issue by protectedMan** [kongzue/DialogV3#133]
我想咨询一下（仅举例，不针对本库）：
1.dialogV2版本（非androidx） ，我使用api 'com.kongzue.dialog:dialog:2.5.2'方式导入我的项目，正常运行不报错。
2.dialogV2版本（非androidx），我使用依赖module的模式直接引用源码到我的项目（如下图）
![image](https://user-images.githubusercontent.com/17565737/76673733-e8bdf980-65e2-11ea-86ea-dea18e18b038.png)，这种情况下，会报错，是关于androidx的错误
![image](https://user-images.githubusercontent.com/17565737/76673738-012e1400-65e3-11ea-83c2-910270348879.png)

我本人的项目是一个androidx项目，所以我就想不懂，这两种引用包的方法为什么一个报错，一个不报错，他们之间有什么不一样的？望回复答疑

**Comment by JingweiWang** [comment]
我猜你没切分支，切了分支重新搞一遍。或者自己改成androidx
