### ISSUE TITLE
BottomMenu布局异常

### ISSUE THREAD

**Issue by protectedMan** [kongzue/DialogV3#136]
![image](https://user-images.githubusercontent.com/17565737/77383260-6b05a500-6dbd-11ea-9f0f-bac0440c4cb9.png)
同样的代码，我的项目显示的效果就是这样 ，不知道是什么原因
3.1.8版本

**Comment by kongzue** [comment]
请处理application样式为Theme.AppCompat.Light.NoActionBar

**Comment by protectedMan** [comment]
我看了下，application是使用的Theme.AppCompat.Light.NoActionBar

**Comment by kongzue** [comment]
我是怀疑如果你没有修改过DialogV3源代码的话，就是style存在问题。目前无法清楚原因在哪里，请重新检查您的项目。

**Comment by protectedMan** [comment]
好的，经过仔细排查，确实我我的style的问题🤝

**Comment by protectedMan** [comment]
问题没有解决， 我theme没有问题的,检查了style确实是Theme.AppCompat.Light.NoActionBar，另外我使用dialogv3的demo，就算不使用Theme.AppCompat.Light.NoActionBar用Theme.AppCompat下面的其他主题也是没有问题的
![image](https://user-images.githubusercontent.com/17565737/77488322-cf813c80-6e6f-11ea-9d8e-b8d83982b604.png)
所以现在看来好像不仅仅是style的问题。

**Comment by protectedMan** [comment]
经过我的实测： 在DialogHelper的refreshDialogPosition方法中，把dialog的window设置为  window.setLayout(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT);
样式就正常了。 在demo上使用也未发现影响demo效果，所以这个问题应该是一个兼容性问题,望能及时更新。

**Comment by kongzue** [comment]
感谢，另外麻烦告知下设备型号和系统版本，我需要做下测试

________________________________
发件人: hai <notifications@github.com>
发送时间: Thursday, March 26, 2020 3:59:45 PM
收件人: kongzue/DialogV3 <DialogV3@noreply.github.com>
抄送: Kongzue <myzcxhh@live.cn>; Comment <comment@noreply.github.com>
主题: Re: [kongzue/DialogV3] BottomMenu布局异常 (#136)


经过我的实测： 在DialogHelper的refreshDialogPosition方法中，把dialog的window设置为 window.setLayout(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT);
样式就正常了。 在demo上使用也未发现影响demo效果，所以这个问题应该是一个兼容性问题,望能及时更新。

―

**Comment by protectedMan** [comment]
目前发现应该是跟项目配置有关，跟机型和系统版本没有关系（5台不同品牌的机子均会复现）。我的解决思路是按照DialogFragment全屏显示的解决方案来处理。

**Comment by protectedMan** [comment]
我这里只有3款机型都出现了这个问题：跑v3的demo没问题，跑自己的项目出现了此问题。我的解决思路是按照下面的文章处理的，参考：https://www.jianshu.com/p/3ecad4bfc55e
根据上述文章我修改了
![image](https://user-images.githubusercontent.com/17565737/77625400-77852b80-6f7e-11ea-86cc-2d1d5a503f68.png)

我这个改法可能是一个临时的，不严谨的做法，希望可以抛砖引玉。

**Comment by kongzue** [comment]
收到，下一个正式版我会加入以下代码确保正确显示：
dialog.getWindow().setLayout(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT);
猜测是因为App环境的Theme导致默认显示特性发生的变化。
