### ISSUE TITLE
Cannot I add a cancel button to Wait Dialog?

### ISSUE THREAD

**Issue by ishomam** [kongzue/DialogV3#137]
Hi. Cannot I add a cancel button to Wait Dialog?
If not please add this feature, this would be helpful.

**Comment by kongzue** [comment]
If you need to press the BACK key to execute the event, you can use this methods:
```
waitDialog.setOnBackClickListener(OnBackClickListener);
```
 Or you can use a custom layout to implement the cancel button:
```
setCustomView(...)
```

**Comment by ishomam** [comment]
Thanks for the quick response.
I wanted something more straightforward to the user than pressing the back button to cancel the process. Also, as I know WaitDialog has no setCustomView(...) method, right?!

**Comment by kongzue** [comment]
In general, WaitDialog is used to force users to wait without allowing them to operate the screen, for example, when user data has been submitted to the server and waiting for a response.
