### ISSUE TITLE
效果很赞的dialog,能不能实现进度条加载类的弹窗呢

### ISSUE THREAD

**Issue by abcdisgreat** [kongzue/DialogV3#14]

**Comment by kongzue** [comment]
您是指哪种加载窗口效果呢？可否给个例子

**Comment by abcdisgreat** [comment]
进度条主要是下载文件时弹窗显示下载进度

**Comment by kongzue** [comment]
我目前不太清楚您的需求，例如正方形WaitDialog加上转圈的进度显示？还是矩形对话框+横向进度条的形式？如果有范例就好了

**Comment by abcdisgreat** [comment]
![}NO~NXLXQ$JL Z@}RQ`F0J7](https://user-images.githubusercontent.com/33865977/59330860-34c2d180-8d25-11e9-8a46-d9b1f4fe63ae.png)
类似这样的，可以更新进度的弹窗

**Comment by kongzue** [comment]
明白了，这种我会单独出一个组件的，目前已经开源在 https://github.com/kongzue/UpdateUI 还没来得及封装
