### ISSUE TITLE
BottomMenu setStyle and setTheme is not working 

### ISSUE THREAD

**Issue by nadeemahmedchanna** [kongzue/DialogV3#140]
BottomMenu.show(ChatRoomActivity.this, ids, new OnMenuItemClickListener() {
            @Override
            public void onClick(String text, int index) {
                //log("点击了：" + text);
                switch (text) {
                    case "Take":
                      //anycode
                        break;
                    case "mute":
                     //anycode
                        break;
                }

            }
        }).setStyle(DialogSettings.STYLE.STYLE_IOS)
                .setCancelable(true)
                .setTitle("CHOOSE ACTION").setTheme(DialogSettings.THEME.DARK);

    }

**Comment by kongzue** [comment]
请使用如下代码:
```
BottomMenu.build(ChatRoomActivity.this)
        .setMenuTextList(ids)
        .setOnMenuItemClickListener(new OnMenuItemClickListener() {
            @Override
            public void onClick(String text, int index) {
                switch (text) {
                    case "Take":
    
                        break;
                    case "mute":
    
                        break;
                }
            }
        })
        .setStyle(DialogSettings.STYLE.STYLE_IOS)
        .setCancelable(true)
        .setTitle("CHOOSE ACTION")
        .setTheme(DialogSettings.THEME.DARK)
        .show();
```
setStyle(...)方法只能在show()前设置。
