### ISSUE TITLE
如何更新CustomDialog中的ui显示

### ISSUE THREAD

**Issue by zhangchaoxu** [kongzue/DialogV3#141]
请教一下，对于已经显示的CustomDialog，如何更新其中的部分组件显示内容？

**Comment by zhangchaoxu** [comment]
里面定义了一个refreshView，但不知道该如何实现

**Comment by kongzue** [comment]
CustomDialog在使用自定义布局时有提供onBind回调，在此回调中会给出根布局rootView，请使用rootView.findViewById(您的view资源id)来获取您布局中的view实例化进行操作

**Comment by zhangchaoxu** [comment]
> CustomDialog在使用自定义布局时有提供onBind回调，在此回调中会给出根布局rootView，请使用rootView.findViewById(您的view资源id)来获取您布局中的view实例化进行操作

感谢答复，从DialogV2用到V3，帮我节省了很多精力。
---
我的问题其实是怎么在dialog的宿主比如Activity中更新dialog中的ui内容，在build的时候确实可以onBind完成dialog的初始ui内容显示，后续activity中有没有什么办法来实现dialog中ui内容的修改，我现在是dialog暴露出一个方法去再次onBind，这样性能消耗比较大，我其实值需要更新ui中的一小部分内容显示，不知道是否有其他更合理的办法，谢谢。

**Comment by kongzue** [comment]
当你将组件实例化对象通过findViewById取出后，并将他们放在全局后，在生命周期内都是可以无限制访问的，例如：
```
private TextView txtTitle;

//...
CustomDialog.build(me, R.layout.layout_custom_dialog, new CustomDialog.OnBindView() {
    @Override
    public void onBind(final CustomDialog dialog, View v) {
        txtTitle = v.findViewById(R.id.txt_title);
        });
    }
}).setAlign(CustomDialog.ALIGN.DEFAULT).setCancelable(false).show();

//...
if(txtTitle!=null){
    txtTitle.setText("这里改变了内容！");
}
```
只要你没有关闭对话框，上述代码中的TextView都可以访问。

**Comment by zhangchaoxu** [comment]
明白了，感谢
