### ISSUE TITLE
我想知道使用通知怎么设置我想要的显示时间

### ISSUE THREAD

**Issue by 1059021214** [kongzue/DialogV3#144]
Notification.show(me, "提示", "提示信息", R.mipmap.ico_wechat, Notification.DURATION_TIME.valueOf(""))

valueOf该怎么使用 我目前只看见Notification.DURATION_TIME.LONG和 Notification.DURATION_TIME.SHORT

我想显示一个通知30秒 来实现通话接听功能

**Comment by kongzue** [comment]
您好，Notification是基于修改Toast来实现的无需悬浮窗权限跨界面提示工具，并不是用于代替系统通知服务的，不支持长时间显示。
