### ISSUE TITLE
模糊效果不可用

### ISSUE THREAD

**Issue by zzxjl1** [kongzue/DialogV3#145]
Error loading RS jni library: java.lang.UnsatisfiedLinkError: JNI_OnLoad failed on a previous attempt to load "/data/app/com.app.toomuchai-8kUQ3Tw2JusAkFUwRR38pw==/lib/arm64/librsjni_androidx.so"

已在混淆中排除renderscript

**Comment by kongzue** [comment]
您好，com.app.toomuchai不是我们的包名，亦不是我们所用其他库的包名。
androidX请使用专用版本：implementation 'com.kongzue.dialog_v3x:dialog:3.1.8'  
另外在软件启动时建议先检查：是否支持Renderscript：
DialogSettings.checkRenderscriptSupport(context)

**Comment by zzxjl1** [comment]
1.切换到debug版本则一切正常
2.此处错误在dialog弹出才后会不断报出

**Comment by kongzue** [comment]
请参考混淆设置：
https://github.com/kongzue/DialogV3#%E6%B7%B7%E6%B7%86%E8%AE%BE%E7%BD%AE
我们在已上线的多个加混淆的项目中未遇到此问题。

**Comment by zzxjl1** [comment]
Changing
`-dontwarn androidx.renderscript.RenderScript.**
-keep public class androidx.renderscript.RenderScript.** { *; }`
into
`-dontwarn androidx.renderscript.**
-keep class androidx.renderscript.** { *; }`
solves the problem.

**Comment by kongzue** [comment]
ok感谢你的反馈，稍后对文档修改
