### ISSUE TITLE
customDialog设置全屏的时候 适配问题

### ISSUE THREAD

**Issue by huangweibin123** [kongzue/DialogV3#146]
customDialog setFullScreen为true的时候，一些安卓手机手机并没有完全的适配。刘海屏的问题，我的手机是vivo v1911A的。就会出现并没有覆盖整个屏幕的问题

**Comment by huangweibin123** [comment]
其实就是全面屏没做好适配的问题

**Comment by kongzue** [comment]
您好，CustomDialog已经遵循Google的标准对刘海屏做了适配，如下图所示，这段代码位于DialogHelper.java:135：
![layoutInDisplayCutoutMode](https://user-images.githubusercontent.com/10115359/79966030-6a952280-84bf-11ea-8b1c-6c02c3e6e501.png)
1.请确认您正在使用最新版本的DialogV3；
2.请于您的设备提供商确认其系统支持此Flag特性，或升级系统以支持此特性；

**Comment by huangweibin123** [comment]
全面屏的还是有些问题。请问大佬，怎么解决

**Comment by huangweibin123** [comment]
我用的最新3.1.9版本的

**Comment by huangweibin123** [comment]
@kongzue 
![591587959573_ pic](https://user-images.githubusercontent.com/26321536/80332639-f3c0a680-887d-11ea-84bf-925b0dfcce17.jpg) 上面我使用了customDialog.setFullScreen(true)。但是我的手机oppo底部和上面的标题栏并没有做好全屏铺满的效果

**Comment by kongzue** [comment]
这中间是张图还是一个布局？

**Comment by huangweibin123** [comment]
@kongzue  是一个布局。ConstraintLayout

**Comment by kongzue** [comment]
目前我只能猜测是安全区的问题，这个需要查相关flag。但目前我们有加入全屏的flag但看你这个情况应该是无效了，没有实机测试我无法得出结论。
不过还是建议类似于这种全屏的情况最好直接使用Activity，因为Dialog在一些特殊情况，例如横竖屏切换时还是不如Activity靠谱

**Comment by huangweibin123** [comment]
@kongzue ok。多谢大佬解答
