### ISSUE TITLE
setCustomDialogStyleId  无法控制进入和离开动画的时间吗？

### ISSUE THREAD

**Issue by ppg408331701** [kongzue/DialogV3#148]
希望动画慢一些，
使用setCustomDialogStyleId  
 `<style name="Coustom_BottomDialog" parent="BaseDialog">
        <item name="android:windowAnimationStyle">@style/coustom_bottomMenuAnim</item>
    </style>

    <style name="coustom_bottomMenuAnim">
        <item name="android:windowEnterAnimation">@anim/bottom_coustom_menu_enter</item>
        <item name="android:windowExitAnimation">@anim/bottom_coustom_menu_exit</item>
    </style>`

`<?xml version="1.0" encoding="utf-8"?>
<set xmlns:android="http://schemas.android.com/apk/res/android">
    <translate
        android:duration="700"
        android:fromYDelta="100%p"
        android:toYDelta="0" />
    <alpha
        android:duration="700"
        android:fromAlpha="0.0"
        android:toAlpha="1.0" />
</set>`

但是无效

**Comment by kongzue** [comment]
目前不支持自定义动画时间，部分动画，例如BottomDialog的进场和离场是在代码中设置的，您可能需要下载代码自行修改。
