### ISSUE TITLE
弹窗有黑色的阴影

### ISSUE THREAD

**Issue by kangjinwen** [kongzue/DialogV3#15]
<img src="http://ww1.sinaimg.cn/large/455fd670gy1g3x1gq909lj20u01t00up.jpg"/>
<img src="http://ww1.sinaimg.cn/large/455fd670gy1g3x1h7u65sj20u01t076f.jpg"/>

等待还有底部弹起的dialog都有黑影,是什么原因呢,从2.9.x.x版本到最新的3.0.5都是这样的呢.

**Comment by kangjinwen** [comment]
希望能提供qq群等交流空间.

**Comment by kongzue** [comment]
1.请尝试Demo是否存在此问题： https://fir.im/DialogV3
2.请检查是否使用自定义样式：DialogSettings.systemDialogStyle 是否被设置了任何值
3.是否使用androidx？
4.请检查您的项目中样式Theme.AppCompat.Light.Dialog是否可以正常访问

**Comment by kangjinwen** [comment]
> 1.请尝试Demo是否存在此问题： https://fir.im/DialogV3
> 2.请检查是否使用自定义样式：DialogSettings.systemDialogStyle 是否被设置了任何值
> 3.是否使用androidx？
> 4.请检查您的项目中样式Theme.AppCompat.Light.Dialog是否可以正常访问
===================================================
1.Demo正常,从git pull的项目编译运行的Demo也正常.
2.初始化配置如下:
 DialogSettings.DEBUGMODE = false;
        DialogSettings.isUseBlur = false;
        DialogSettings.style = DialogSettings.STYLE.STYLE_IOS;
        DialogSettings.theme = DialogSettings.THEME.LIGHT;
        DialogSettings.cancelable = false;
![image](https://user-images.githubusercontent.com/18061486/59246930-5f8f2600-8c50-11e9-9dd2-99c43c5d2100.png)
3.没有使用androidx
4.Theme.AppCompat.Light.Dialog可以正常访问.
![image](https://user-images.githubusercontent.com/18061486/59246958-7e8db800-8c50-11e9-9a52-84e7bb8bf27f.png)

**Comment by kongzue** [comment]
那就不清楚了，我能怀疑到的只是你的style存在问题，但目前来看应该不是。
另外就是需要检查下API版本，我觉得你这个应该是不知道什么原因变成了Android 4.x的style导致的
