### ISSUE TITLE
dialog显示的时候，状态栏的文字会变白色，可以指点一下在哪里改吗？

### ISSUE THREAD

**Issue by ppg408331701** [kongzue/DialogV3#157]
产品有个麻烦的需求，  普通的dialog弹出时有半透明的背景。
但是WaitDialog和TipDialog 弹出的时候要完全透明的背景。

我这边虽然可以通过setCustomDialogStyleId自定义弹出时候的背景。但是状态栏的文字会深色模式。

希望能指点一下在哪里改这个功能，我拉源码下来改改

**Comment by kongzue** [comment]
您可以修改Module中res/values/styles.xml中的如下属性：
```
<item name="android:backgroundDimAmount">0.4</item>
```
它是控制背景遮罩透明度的。

**Comment by ppg408331701** [comment]
![Screenshot_2020-06-05-15-12-40-720_com kongzue di](https://user-images.githubusercontent.com/16531268/83847766-648d9500-a73f-11ea-8d8c-cef2643933ba.jpg)


我指的的是，dialog弹出时，状态栏的文字会从黑色变成白色，我看了源码，似乎您在tipdialog和waitDialog没有对状态栏操作，所以请问状态栏从黑变白是系统的行为吗？

**Comment by kongzue** [comment]
状态栏颜色默认是由dialog的window的decorView的Flag(SYSTEM_UI_FLAG_LIGHT_STATUS_BAR)控制的，但不清楚为什么，在Dialog的SYSTEM_UI_FLAG_LIGHT_STATUS_BAR设置时是无效的。

**Comment by ppg408331701** [comment]
怪不得，我昨晚试了几小时都没成。谢谢了，我单独为tipdialog和waitDialog写一个吧
