### ISSUE TITLE
怎么让对话框弹出时，最外层的背景不变暗

### ISSUE THREAD

**Issue by kdwu** [kongzue/DialogV3#159]
怎么让对话框弹出时，最外层的背景不变暗

**Comment by kongzue** [comment]
您可以自定义style或修改Module中res/values/styles.xml中的如下属性：
```
<item name="android:backgroundDimAmount">0.4</item>
```
它是控制背景遮罩透明度的。

**Comment by kdwu** [comment]
> 您可以自定义style或修改Module中res/values/styles.xml中的如下属性：
> 
> ```
> <item name="android:backgroundDimAmount">0.4</item>
> ```
> 
> 它是控制背景遮罩透明度的。

好的，谢谢您的回答
