### ISSUE TITLE
BottomMenu弹出之后点击外部取消，跳转一个页面，回来之后就又显示了

### ISSUE THREAD

**Issue by ling9400** [kongzue/DialogV3#16]
如题：并且还是显示两次

**Comment by kongzue** [comment]
是最新版本么？

**Comment by ling9400** [comment]
@kongzue 是的，用你的demo也是一样的效果

**Comment by kongzue** [comment]
我这边没有成功复现此问题，版本3.0.5

![Video_20190612_123653_71](https://user-images.githubusercontent.com/10115359/59323828-ed314b00-8d0e-11e9-9860-636c83962cc7.gif)

**Comment by ling9400** [comment]
最新版的没有这个问题了，我是用library的形式引入的3.0.4的代码，看了你的更新说明是做了修改的。

**Comment by kongzue** [comment]
嗯，这个是之前已知bug，3.0.5更新日志如下：

**Comment by kongzue** [comment]
BottomMenu 和 ShareDialog 的 IOS 风格新增暗色模式，其他风格后续跟进；
根据 IOS13 实际效果对所有暗色模式颜色进行了调整；
修复了切换 Activity 导致已经 dismiss 的 Dialog 重复出现的 bug；
修复了 dismissEvent 可能引发的空指针异常；
