### ISSUE TITLE
请问中间弹出列表对话框，怎么实现

### ISSUE THREAD

**Issue by Android-wangmeng** [kongzue/DialogV3#160]
如题，不需要底部弹出。

**Comment by kongzue** [comment]
您好，目前BottomDialog不支持修改弹出位置，您可以尝试自定义对话框CustomDialog或者自行修改Module实现。

**Comment by Android-wangmeng** [comment]
好的，Dialog弹出的动画时间能否修改？

**Comment by kongzue** [comment]
您好，最新版本支持了所有对话框组件setAlign(...)方法，均可自定义显示位置，请更新至3.2.0正式版或内测版3.2.0.3
