### ISSUE TITLE
依然崩溃报错  defaultConfig 添加过了

### ISSUE THREAD

**Issue by xiaolongbao22333** [kongzue/DialogV3#166]
java.lang.ExceptionInInitializerError
    │ 	at com.kongzue.dialog.v3.TipDialog$6.run(TipDialog.java:338)
    │ 	at android.os.Handler.handleCallback(Handler.java:883)
    │ 	at android.os.Handler.dispatchMessage(Handler.java:100)
    │ 	at android.os.Looper.loop(Looper.java:244)
    │ 	at android.app.ActivityThread.main(ActivityThread.java:7523)
    │ 	at java.lang.reflect.Method.invoke(Native Method)
    │ 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
    │ 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1020)
    │ Caused by: java.lang.RuntimeException: 
错误！
RenderScript支持库未启用，要启用模糊效果，请在您的app的Gradle配置文件中添加以下语句：
android { 
...
  defaultConfig { 
    ...
    renderscriptTargetApi 17 
    renderscriptSupportModeEnabled true 
  }
}

**Comment by kongzue** [comment]
请尝试运行Demo看是否正常，如果也不正常，说明设备不支持RenderScript，请关闭模糊效果（详见文档），若可以正常运行，请检查自己的项目配置是否正常。

**Comment by xiaolongbao22333** [comment]
> 请尝试运行Demo看是否正常，如果也不正常，说明设备不支持RenderScript，请关闭模糊效果（详见文档），若可以正常运行，请检查自己的项目配置是否正常。

 BlurView.class.getClassLoader().loadClass("android.support.v8.renderscript.RenderScript");//BlurView
DialogSettings.checkRenderscriptSupport()

反射的原因  换成了现有的 就能用了
BlurView.class.getClassLoader().loadClass("android.renderscript.RenderScript");
DialogSettings.class.getClassLoader().loadClass("android.graphics.drawable.Drawable");
DialogSettings.class.getClassLoader().loadClass(" android.renderscript.RenderScript");
