### ISSUE TITLE
3.2.1版本的WebView无法上下滑动，但提供的供下载的Kongzue Dialog V3 Demo 演示程序可以滑动，可能是3.2.0版本的apk文件

### ISSUE THREAD

**Issue by ouwp** [kongzue/DialogV3#170]

**Comment by kongzue** [comment]
如果您正在使用Support版本，可以尝试升级至3.2.1.1测试版本

**Comment by ouwp** [comment]
> 如果您正在使用Support版本，可以尝试升级至3.2.1.1测试版本

3.2.2 版本还是不行呀，老板

**Comment by kongzue** [comment]
经过测试，可以正常滑动WebView

**Comment by ouwp** [comment]
> 经过测试，可以正常滑动WebView

荣耀9，EMUI版本9.1.0，Android版本9， 使用的是此项目AndroidX版本最新的demo，无法滑动。

**Comment by ouwp** [comment]
> 经过测试，可以正常滑动WebView

模拟器，Andriod10，使用的是此项目AndroidX版本最新的demo，也无法滑动。

**Comment by ouwp** [comment]
> 经过测试，可以正常滑动WebView

唯一能滑动的，是您通过链接提供的3.2.0版本的 演示Demo，3.2.1，3.2.2都是通过代码编译的，都不可以滑动，唯一改过的地方是以下两个地方
com.android.tools.build:gradle:4.0.1
distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip

**Comment by kongzue** [comment]
你试一下 3.2.2.2 测试版本（AndroidX）

**Comment by ouwp** [comment]
> 你试一下 3.2.2.2 测试版本（AndroidX）
implementation 'com.kongzue.dialog_v3x:dialog:3.2.2.2'
不行，配置和上面一样

**Comment by ouwp** [comment]
> 你试一下 3.2.2.2 测试版本（AndroidX）

implementation 'com.kongzue.dialog_v3x:dialog:3.2.2.2'
不行，配置和上面相同

**Comment by kongzue** [comment]
我有点怀疑你手机有问题了......

**Comment by kongzue** [comment]
很抱歉刚刚查了一下应该是分支同步出问题了，导致InterceptYLinearLayout并未实现代码同步，请更新至3.2.2.3版本在进行测试

**Comment by ouwp** [comment]
> 很抱歉刚刚查了一下应该是分支同步出问题了，导致InterceptYLinearLayout并未实现代码同步，请更新至3.2.2.3版本在进行测试
implementation 'com.kongzue.dialog_v3x:dialog:3.2.2.3'
Failed to resolve: dialog-3.2.2.3
Affected Modules: main
没有这个版本啊0-0

**Comment by ouwp** [comment]
> 很抱歉刚刚查了一下应该是分支同步出问题了，导致InterceptYLinearLayout并未实现代码同步，请更新至3.2.2.3版本在进行测试

implementation 'com.kongzue.dialog_v3x:dialog:3.2.2.3'
Failed to resolve: dialog-3.2.2.3
Affected Modules: main
没有这个版本啊0-0

**Comment by kongzue** [comment]
已确认有这个版本：https://bintray.com/myzchh/maven/dialogV3X/3.2.2.3

**Comment by ouwp** [comment]
> 已确认有这个版本：https://bintray.com/myzchh/maven/dialogV3X/3.2.2.3

但是我真的是同步不下来，用的就是这条啊
implementation 'com.kongzue.dialog_v3x:dialog:3.2.2.3'

**Comment by kongzue** [comment]
请检查是否配置代理，或代理Maven服务，例如阿里云中转服务，或者您可以通过上述链接下载aar包手动引入：
https://bintray.com/myzchh/maven/dialogV3X/3.2.2.3#files/com%2Fkongzue%2Fdialog_v3x%2Fdialog%2F3.2.2.3

**Comment by kongzue** [comment]
手动导入方法：https://www.jianshu.com/p/4903faf4816b

**Comment by ouwp** [comment]
> 请检查是否配置代理，或代理Maven服务，例如阿里云中转服务，或者您可以通过上述链接下载aar包手动引入：
> https://bintray.com/myzchh/maven/dialogV3X/3.2.2.3#files/com%2Fkongzue%2Fdialog_v3x%2Fdialog%2F3.2.2.3

额，这，怎么讲呢，只有你说的3.2.2.3拉不下来，其他的都没问题，包括这个项目的其他版本，还是其他项目都没问题

**Comment by kongzue** [comment]
已经更新到正式版了，你可以再试下

**Comment by ouwp** [comment]
> 已经更新到正式版了，你可以再试下

没问题，可以滑动了
