### ISSUE TITLE
一个建议，是否可以让MessageDialog支持传入SpannableString

### ISSUE THREAD

**Issue by ppg408331701** [kongzue/DialogV3#171]
![TIM截图20200720171736](https://user-images.githubusercontent.com/16531268/87921307-f281cd00-caac-11ea-9988-9794bfe7cc7d.png)

类似这样的对话框，部分文字需要变色的情况下，用customDialog太浪费了，如果在外面构建好SpannableString直接传入MessageDialog.show就方便很多了

```
public static MessageDialog show(@NonNull AppCompatActivity context, String title, SpannableString message, String okButton, String cancelButton) {
        synchronized (MessageDialog.class) {
            MessageDialog messageDialog = show(context, title, message, okButton, cancelButton, null);
            return messageDialog;
        }
    }
```

**Comment by kongzue** [comment]
您好，如果您正在使用Support版本，请更新至 3.2.1.3 测试版本，或等待正式版本更新，如果您正在使用 AndroidX 版本，请等待正式版更新。
经过评定，我决定将 DialogV3 的文本传入参数类型修改为 CharSequence，因为该接口可一并兼容 String 作为参数及 SpannableString 作为参数，这可能导致一些代码需要修改，诸如 BottomMenu 的回调参数类型由 String 改为了 CharSequence。
