### ISSUE TITLE
小米5s上Notification显示时间很短

### ISSUE THREAD

**Issue by xsjqqq123** [kongzue/DialogV3#179]
如题，半秒钟不到，它就消失了。是否是系统本身的问题？

**Comment by kongzue** [comment]
Notification依赖Toast进行实现（目前因为高版本Android不在支持自定义Toast，所以依赖悬浮窗的实现还处于内测开发阶段），因此显示时长受系统Toast控制，无法进行修改。

**Comment by kongzue** [comment]
您好，长时间未收到回复暂时关闭此问题，如有疑问可以继续回复。
