### ISSUE TITLE
InputDialog 没有 addTextWatcher 方法，无法限制输入文本

### ISSUE THREAD

**Issue by cv0cv0** [kongzue/DialogV3#18]
比如限制小数的位数。

**Comment by kongzue** [comment]
目前尚不支持此功能，后续会增加getEditView() 方法暴露编辑框组件

**Comment by kongzue** [comment]
请更新至 3.0.8 版本，InputDialog 新增 getEditTextView() 可以自行对文本框进行一些事件或属性处理；
