### ISSUE TITLE
关于多语言设置中，在切换English时，发现使用了DialogV3的弹框中的内容未切换成功!!!

### ISSUE THREAD

**Issue by Amoour** [kongzue/DialogV3#181]
关于多语言设置中，在切换English时，发现使用了DialogV3的弹框中的内容未切换成功，大佬，有发现过这个问题吗？还是我这边的问题呢？求解答

**Comment by kongzue** [comment]
建议使用string多语言资源文件配置Dialog，其次，并不能在显示Dialog过程中切换，需要重启Dialog

**Comment by kongzue** [comment]
您好，长时间未收到回复暂时关闭此问题，如有疑问可以继续回复。
