### ISSUE TITLE
STYLE_KONGZUE  的MessageDialog不能使用setBackgroundResId吗？

### ISSUE THREAD

**Issue by ppg408331701** [kongzue/DialogV3#186]
我看了一下源码，只有STYLE_IOS和STYLE_MIUI才设置backgroundResId，STYLE_KONGZUE只能设置backgroundColor

**Comment by kongzue** [comment]
您好，Kongzue风格与Material风格是使用默认Dialog样式实现的，不能修改对话框背景

**Comment by ppg408331701** [comment]
好的，看来只能改ios风格了。谢谢
