### ISSUE TITLE
按钮的摆放位置

### ISSUE THREAD

**Issue by xiaoduv587** [kongzue/DialogV3#19]
老哥，按钮的摆放位置，比如确认和取消的，怎么调换下他们俩的位置

**Comment by kongzue** [comment]
MessageDialog.show(MainActivity.this, "提示", "这是一条双按钮消息", "确定", "取消");
替换为
MessageDialog.show(MainActivity.this, "提示", "这是一条双按钮消息", "取消", "确定");
没问题的，至于事件也是反过来写就行
