### ISSUE TITLE
DialogSettings.style = DialogSettings.STYLE.STYLE_MATERIAL

### ISSUE THREAD

**Issue by VainAnts** [kongzue/DialogV3#196]
STYLE.STYLE_MATERIAL 设置TextInfo无效，是出于什么原因关掉这个功能了

**Comment by kongzue** [comment]
您设置的是哪个TextInfo呢

**Comment by VainAnts** [comment]
MessageDialog..setMessageTextInfo(new TextInfo().setGravity(Gravity.LEFT).setFontColor(Color.RED))

**Comment by kongzue** [comment]
您好，我这边检查了代码，应该是Google修改了AlertDialog成员名称导致的。因为AlertDialog并未提供修改样式接口，这里是使用反射实现的，我会尝试解决。

**Comment by VainAnts** [comment]
感谢您的及时回复，我先用3.2.2版本吧，这个版本可以修改
