### ISSUE TITLE
这bug绝了，在小屏手机中

### ISSUE THREAD

**Issue by stytooldex** [kongzue/DialogV3#197]
自定义布局后就没见下面布局了

**Comment by stytooldex** [comment]
![1352226f4ee85eb1.jpg](https://user-images.githubusercontent.com/20622721/92850983-ad7c7600-f41f-11ea-9bd1-2a8c3d514689.jpg)

**Comment by kongzue** [comment]
请在你的布局最外围套一层ScrollView....................

**Comment by stytooldex** [comment]
> 请在你的布局最外围套一层ScrollView....................

你觉得行？😏要不你自己也试试

**Comment by kongzue** [comment]
你可以把你的XML给过来我试试看

**Comment by kongzue** [comment]
您好，长时间未收到回复暂时关闭此问题，如有疑问可以继续回复。
