### ISSUE TITLE
在封装的网络请求里边使用，会出现闪退现象

### ISSUE THREAD

**Issue by jackandroid2016** [kongzue/DialogV3#2]

**Comment by kongzue** [comment]
1，请确保在主线程使用，如果有用Kongzue提供的网络框架是不存在此问题的。
2，请提供详细闪退崩溃日志，目前无法确定问题原因

**Comment by jackandroid2016** [comment]
是ANR了，没有崩溃日志，同时多个接口请求会有这个问题

**Comment by kongzue** [comment]
无法推断原因。
目前我这边在用的组合就是 [kongzue/BaseOkHttpV3](https://github.com/kongzue/BaseOkHttpV3) 以及[kongzue/DialogV3](https://github.com/kongzue/DialogV3) 且在多个已上架的项目中应用，并未遇到任何问题。
DialogV3本质上是DialogFragment的封装，提供更方便的创建方式和接口，理论上不存在您所描述的问题。
