### ISSUE TITLE
com.kongzue.dialog_v3x:dialog可没有3.2.4  

### ISSUE THREAD

**Issue by stytooldex** [kongzue/DialogV3#202]
害

**Comment by kongzue** [comment]
您好，有。
https://bintray.com/myzchh/maven/dialogV3X

**Comment by kongzue** [comment]
3.2.4版本：https://bintray.com/myzchh/maven/dialogV3X/3.2.4

**Comment by kongzue** [comment]
您好，长时间未收到回复暂时关闭此问题，如有疑问可以继续回复。
