### ISSUE TITLE
BottomMenu 不能设置强制选择吗？设置了点击外部不消失，但是顶部还有个横杠可以拖拉消失。。。还是说有设置的方法我不知道呀

### ISSUE THREAD

**Issue by MMZZLOVE** [kongzue/DialogV3#203]

**Comment by kongzue** [comment]
目前Material风格本身自带滑动关闭功能，这个将在未来的版本中判断当cancelable不允许时移除

**Comment by kongzue** [comment]
您好，感谢您的反馈，此问题已经在3.2.4.3（Support）测试版中被修复，AndroidX版本可能需要等到下一个正式版更新。
