### ISSUE TITLE
jcenter上最新版是3.2.4.2，请问是修复了什么吗？

### ISSUE THREAD

**Issue by ppg408331701** [kongzue/DialogV3#205]
和3.2.4.1相比

**Comment by ppg408331701** [comment]
希望发布新版的时候能顺便更新一下github一份

**Comment by kongzue** [comment]
目前只会发布正式版到github，因为测试版不排除还有不稳定的问题

________________________________
发件人: ppg408331701 <notifications@github.com>
发送时间: Tuesday, October 13, 2020 5:29:54 PM
收件人: kongzue/DialogV3 <DialogV3@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: Re: [kongzue/DialogV3] jcenter上最新版是3.2.4.2，请问是修复了什么吗？ (#205)


希望发布新版的时候能顺便更新一下github一份

―

**Comment by ppg408331701** [comment]
主要是3.2.4那个setMenuTextList的bug在3.2.4.1修复了，所以我现在要发更新包，不知道要用3.2.4.1还是3.2.4.2

**Comment by kongzue** [comment]
我找时间发一下版吧，大概在明天

________________________________
发件人: ppg408331701 <notifications@github.com>
发送时间: Tuesday, October 13, 2020 5:35:07 PM
收件人: kongzue/DialogV3 <DialogV3@noreply.github.com>
抄送: Kongzue <myzcxhh@live.cn>; Comment <comment@noreply.github.com>
主题: Re: [kongzue/DialogV3] jcenter上最新版是3.2.4.2，请问是修复了什么吗？ (#205)


主要是3.2.4那个setMenuTextList的bug在3.2.4.1修复了，所以我现在要发更新包，不知道要用3.2.4.1还是3.2.4.2

―

**Comment by kongzue** [comment]
已经同步最新的代码到Github，问题修复日志请参照log或者readme最底下的更新日志
