### ISSUE TITLE
FullScreenDialog 自定义布局中包含 tablayout 和 viewpager 时，抛出无法找到对应view异常

### ISSUE THREAD

**Issue by ChannelCook** [kongzue/DialogV3#208]
FullScreenDialog 自定义布局中包含 tablayout 和 viewpager 时，抛出无法找到对应view异常

**Comment by kongzue** [comment]
您好，在最新版本中无法复现您所述的问题。经过检查，在FullScreenDialog中使用TableLayout和ViewPager完全正常，测试代码如下：
布局文件layout_test.xml:
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical" android:layout_width="match_parent"
    android:layout_height="match_parent">

    <TableLayout
        android:id="@+id/tableLayout"
        android:layout_width="match_parent"
        android:layout_height="30dp"/>

    <android.support.v4.view.ViewPager
        android:id="@+id/viewpager"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>
</LinearLayout>
```
测试代码：
```
    private TableLayout tableLayout;
    private ViewPager viewpager;

//执行代码
FullScreenDialog.show(me, R.layout.layout_test, new FullScreenDialog.OnBindView() {
    @Override
    public void onBind(FullScreenDialog dialog, View rootView) {
        tableLayout = rootView.findViewById(R.id.tableLayout);
        viewpager = rootView.findViewById(R.id.viewpager);
        
        log("tableLayout==null?" + (tableLayout==null));
        log("viewpager==null?" + (viewpager==null));
    }
});
```
输出结果：
```
tableLayout==null?false
viewpager==null?false
```

**Comment by ChannelCook** [comment]
No view found for id 0x7f090218 (com.xxx:id/view_pager) for fragment
![Screen Shot 2020-10-15 at 23 56 15](https://user-images.githubusercontent.com/67857773/96155051-120c8280-0f42-11eb-8023-babcc12573d5.png)

**Comment by kongzue** [comment]
那么我这边帮不到你了，因为无法复现你的问题

________________________________
发件人: ChannelCook <notifications@github.com>
发送时间: Thursday, October 15, 2020 11:57:07 PM
收件人: kongzue/DialogV3 <DialogV3@noreply.github.com>
抄送: Kongzue <myzcxhh@live.cn>; Comment <comment@noreply.github.com>
主题: Re: [kongzue/DialogV3] FullScreenDialog 自定义布局中包含 tablayout 和 viewpager 时，抛出无法找到对应view异常 (#208)


No view found for id 0x7f090218 (com.xxx:id/view_pager) for fragment
[Screen Shot 2020-10-15 at 23 56 15]<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F67857773%2F96155051-120c8280-0f42-11eb-8023-babcc12573d5.png&data=04%7C01%7C%7C8a9b4616c0d84a0c674708d87122f8f0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637383742297504276%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=rKPWCLJ9YJQyxam1tUArcJmiXb1zNMAJSEqntLydOj0%3D&reserved=0>

―

**Comment by ChannelCook** [comment]
testing
