### ISSUE TITLE
CustomDialog 设置全屏时无法盖住BottomNavigationView

### ISSUE THREAD

**Issue by ChannelCook** [kongzue/DialogV3#209]
CustomDialog.build((AppCompatActivity) getActivity(), R.layout.tips, new CustomDialog.OnBindView() {
                @Override
                public void onBind(final CustomDialog dialog, View v) {
                    //logic code here
                }
            })
            .setFullScreen(true)
            .show();

**Comment by kongzue** [comment]
目前确实是会直接绕过“非安全区”的

**Comment by ff-frida** [comment]
> ```
>         CustomDialog.build((AppCompatActivity) getActivity(), R.layout.tips, new CustomDialog.OnBindView() {
>             @Override
>             public void onBind(final CustomDialog dialog, View v) {
>                 //logic code here
>             }
>         })
>         .setFullScreen(true)
>         .show();
> ```

我也遇到同样的问题，我需要一个全屏的dialog，里面铺面内容，发现底部有空隙，横屏的时候，右边有空隙，请问你解决了么
