### ISSUE TITLE
Notification 点击事件无效

### ISSUE THREAD

**Issue by nxnyk** [kongzue/DialogV3#210]

**Comment by nxnyk** [comment]
点击事件 和消失都没有触发

**Comment by kongzue** [comment]
此问题在文档正文中有写为什么... https://github.com/kongzue/DialogV3#%E9%80%9A%E7%9F%A5

**Comment by nxnyk** [comment]
> 此问题在文档正文中有写为什么... https://github.com/kongzue/DialogV3#%E9%80%9A%E7%9F%A5

也就是说要写想点击，就必须要申请权限咯

**Comment by kongzue** [comment]
Google在新版本强行这么变更我也没办法啊，除非去定制ROM...这个我实在做不到

**Comment by nxnyk** [comment]
> Google在新版本强行这么变更我也没办法啊，除非去定制ROM...这个我实在做不到

哈哈，麻烦作者了，我试试用自定义dialog，从顶部弹出解决吧

**Comment by kongzue** [comment]
你可以试试悬浮窗方法：Notification.mode = Notification.Mode.FLOATING_WINDOW;

**Comment by kongzue** [comment]
反射Toast在新版本Android中不可用，目前能实现的方案也就只有悬浮窗了

**Comment by nxnyk** [comment]
> 反射Toast在新版本Android中不可用，目前能实现的方案也就只有悬浮窗了

悬浮窗要权限的 太不友好了。。可以没有点击，但是不能让用户都去做一个操作。。产品要求。。

**Comment by kongzue** [comment]
Google现在就是从原理上在恶心人，Dialog必须依赖Activity实现，而跨界面显示的Dialog就根本无法做到，Toast本质上也就是个可以跨屏显示的例外Window，但现在也不被允许反射了

**Comment by nxnyk** [comment]
> Google现在就是从原理上在恶心人，Dialog必须依赖Activity实现，而跨界面显示的Dialog就根本无法做到，Toast本质上也就是个可以跨屏显示的例外Window，但现在也不被允许反射了

好吧，现在谷歌的权限是越来越严格了，11都没办法直接获取存储权限了。。唉 难啊
