### ISSUE TITLE
WaitDialog setCancelable(false)感觉没有效果

### ISSUE THREAD

**Issue by oudengding** [kongzue/DialogV3#211]
如题，这种情况基本发生在网络请求后，不知是什么原因

**Comment by oudengding** [comment]
进行网络请求前，启用弹窗
销毁方法是在网络请求返回结果中调用，但很多时候弹窗都是提前自动消失的

**Comment by kongzue** [comment]
您好，需要关闭WaitDialog请使用dismiss()方法。WaitDialog本身Cancelable就是false的，请尝试在下载运行Demo，尝试复现相同的问题

**Comment by oudengding** [comment]
> 您好，需要关闭WaitDialog请使用dismiss()方法。WaitDialog本身Cancelable就是false的，请尝试在下载运行Demo，尝试复现相同的问题

好的
