### ISSUE TITLE
使用bottommenu，在android6.0.1上点击无反应

### ISSUE THREAD

**Issue by wlxfxy** [kongzue/DialogV3#22]

**Comment by kongzue** [comment]
很抱歉，未查询到Google官方发布的android6.0.1版本官方镜像，无法进行测试...

**Comment by kongzue** [comment]
![AVD](https://user-images.githubusercontent.com/10115359/60252594-14863b80-98fd-11e9-8c7d-b76c17186f7e.png)

**Comment by kongzue** [comment]
我正在基于6.0.0版本的Android虚拟机上进行测试，稍后给您测试报告

**Comment by wlxfxy** [comment]
我测试是在OPPOR9s上，android版本应该是6.0.1，点击无反应

**Comment by kongzue** [comment]
好的，稍后我会在云测上进行测试

**Comment by wlxfxy** [comment]
好的，谢谢了

**Comment by kongzue** [comment]
通过测试，在OPPO R9s with Android 6.0.1上没有发现此问题
![测试](https://user-images.githubusercontent.com/10115359/60253500-d68a1700-98fe-11e9-8f78-8cedca3a9d2b.jpg)

**Comment by wlxfxy** [comment]
我这边测试就这一个手机上有问题，不知道怎么回事

**Comment by kongzue** [comment]
这需要大量的报告数据才能推断问题的结论，目前无法确定问题的原因，我会记录并跟踪此问题，如果发现解决此问题的办法也会在第一时间更新版本。
