### ISSUE TITLE
tipdialog 崩溃

### ISSUE THREAD

**Issue by creativityingenuity** [kongzue/DialogV3#227]
![图片](https://user-images.githubusercontent.com/12170093/104264942-85814a00-54c7-11eb-91ba-0ea6d3fd65c1.png)

**Comment by kongzue** [comment]
请更新至最新版本以修复此问题：3.2.5
更推荐尽快迁移至[DialogX](https://github.com/kongzue/DialogX)，V3将在不久停止更新。

**Comment by creativityingenuity** [comment]
幸好更新了，要不我得手动改了 thx
