### ISSUE TITLE
您好！自定义的customdialog，怎么设置cancelable，或者怎么让返回键和区域外点击失效呢？

### ISSUE THREAD

**Issue by wwdn** [kongzue/DialogV3#23]
您好！自定义的customdialog，怎么设置cancelable，或者怎么让返回键和区域外点击失效呢？

**Comment by kongzue** [comment]
请更新至 3.0.8.4 版本，提供了 CustomDialog 的 setCancelable(boolean) 方法用于设置是否允许点击外部区域关闭 CustomDialog 。
该版本尚处于内测阶段，如有问题请随时联系我，正式版会在稍后更新。

**Comment by wwdn** [comment]
您好！在适配1080P 密度是1的屏幕的时候，显示不全，设置了全屏之后，内容显示的高度左右两边没办法点击消失？只有上下空白可以点击消失。customDialog能拿到dialog对象吗？从而设置一些宽高和原生的一些监听，比如dispatchevent之类的

**Comment by wwdn** [comment]
customDialog.dialog.getDialog() 为null 怎么能拿到Dialog对象呢？

**Comment by kongzue** [comment]
请在OnShow后获取
