### ISSUE TITLE
希望明暗主题可以跟随app全局主题

### ISSUE THREAD

**Issue by fengyuecanzhu** [kongzue/DialogV3#232]
希望明暗主题可以跟随app全局主题，比如如果app切到夜间主题，dialog能够自动暗主题，而不用手动改一下主题

**Comment by kongzue** [comment]
这个主要问题是没办法入侵Activity的onConfigurationChanged方法来进行相关处理，而且会涉及到Dialog的重启导致数据丢失的问题

**Comment by fengyuecanzhu** [comment]
> 这个主要问题是没办法入侵Activity的onConfigurationChanged方法来进行相关处理，而且会涉及到Dialog的重启导致数据丢失的问题

**Comment by fengyuecanzhu** [comment]
> 这个主要问题是没办法入侵Activity的onConfigurationChanged方法来进行相关处理，而且会涉及到Dialog的重启导致数据丢失的问题

我感觉可以在像app一样加个value-night夜间样式，不知道这样行不行

**Comment by kongzue** [comment]
做不到，因为DialogV3的主题不是基于XML结构的style进行设计的

**Comment by fengyuecanzhu** [comment]
> 做不到，因为DialogV3的主题不是基于XML结构的style进行设计的

哦，好吧
