### ISSUE TITLE
loading 如何去掉背景变暗

### ISSUE THREAD

**Issue by jackandroid2016** [kongzue/DialogV3#26]

**Comment by kongzue** [comment]
请使用全局设置自定义dialog风格：
```
DialogSettings.systemDialogStyle = R.style.CustomDialogTheme;
```
请进入您的项目，res/values/styles.xml 创建 CustomDialogTheme的样式：
```
<style name="DialogTheme" parent="BaseDialog">
    <item name="android:backgroundDimAmount">0</item>
</style>
```
运行即可。

**Comment by jackandroid2016** [comment]
ok，谢谢
| |
zlmeet
|
|
zlmeet@163.com
|
签名由网易邮箱大师定制
在2019年7月5日 16:34，Kongzue<notifications@github.com> 写道：

请使用全局设置自定义dialog风格：

DialogSettings.systemDialogStyle = R.style.CustomDialogTheme;



请进入您的项目，res/values/styles.xml 创建 CustomDialogTheme的样式：

<style name="DialogTheme" parent="BaseDialog">

    <item name="android:backgroundDimAmount">0</item>

</style>



运行即可。

**Comment by jackandroid2016** [comment]
我想仅仅是加载框是无背景的，其他的还是存在，这个地方还能再优化吗？
| |
zlmeet
|
|
zlmeet@163.com
|
签名由网易邮箱大师定制
在2019年7月5日 16:34，Kongzue<notifications@github.com> 写道：

请使用全局设置自定义dialog风格：

DialogSettings.systemDialogStyle = R.style.CustomDialogTheme;



请进入您的项目，res/values/styles.xml 创建 CustomDialogTheme的样式：

<style name="DialogTheme" parent="BaseDialog">

    <item name="android:backgroundDimAmount">0</item>

</style>



运行即可。

**Comment by kongzue** [comment]
目前尚不支持单独设置 style，但这个需求会在后续版本更新
