### ISSUE TITLE
iOS风格标题太长没有边距

### ISSUE THREAD

**Issue by EricsXcode** [kongzue/DialogV3#27]
你好！在设置为iOS风格时，标题太长时建议您设置一个边距。还有如果消息内容太长，可能无法显示，建议设置一个最大的高度，用scrollview来包裹消息内容。 iOS风格的动画也略显延迟。感谢你的分享。

**Comment by kongzue** [comment]
您好，标题部分不建议使用长文本。一般而言，提示框设计标准为标题仅使用“提示”、“警告”等简洁明了的提示语而在正文部分显示消息内容，对于消息部分，会在后续版本增加滚动特性。iOS风格动画本身不具有延迟设定，请检查您的设备是否在执行renderscript时存在效率问题，若存在，请通过以下语句关闭模糊效果：
```
DialogSettings.isUseBlur = false;
```

**Comment by EricsXcode** [comment]
谢谢您的分享！ 我已下载源码自己修改，期待您的后续更新。
