### ISSUE TITLE
首页开始下载的时候，然后点击停止下载有问题

### ISSUE THREAD

**Issue by rcj60560** [kongzue/DialogV3#29]
RT

**Comment by kongzue** [comment]
很抱歉，DialogV3不提供下载功能，如有需要您可以尝试BaseaOkHttp

________________________________
发件人: luo <notifications@github.com>
发送时间: Sunday, July 14, 2019 3:24:37 PM
收件人: kongzue/DialogV3
抄送: Subscribed
主题: [kongzue/DialogV3] 首页开始下载的时候，然后点击停止下载有问题 (#29)


RT

―

**Comment by rcj60560** [comment]
@kongzue 谢谢 我学习一哈
