### ISSUE TITLE
Android 5.0.2出现闪退

### ISSUE THREAD

**Issue by byteluo** [kongzue/DialogV3#30]
在vivo Y35A  Android 5.0.2时，调用MessageDialog.show()方法出现闪退

**Comment by kongzue** [comment]
您好，暂时我无法得到vivo Y35A进行测试，以下是在Y85A上的测试结果，均未发现任何问题 ：
![1](https://user-images.githubusercontent.com/10115359/61308376-bb863500-a822-11e9-86e3-82eec19a1869.png)
![2](https://user-images.githubusercontent.com/10115359/61308378-bc1ecb80-a822-11e9-8dd7-8b0e23411b5c.png)
![3](https://user-images.githubusercontent.com/10115359/61308379-bc1ecb80-a822-11e9-8e06-e6a88c3efba9.png)
![4](https://user-images.githubusercontent.com/10115359/61308380-bcb76200-a822-11e9-9d1a-a4d90bed8737.png)
![5](https://user-images.githubusercontent.com/10115359/61308381-bcb76200-a822-11e9-94aa-e7480da6f23d.png)
![6](https://user-images.githubusercontent.com/10115359/61308382-bd4ff880-a822-11e9-84fd-201b89cab7f2.png)
![7](https://user-images.githubusercontent.com/10115359/61308383-bd4ff880-a822-11e9-9b1d-56c57a4897b0.png)
稍后我会尽可能尝试寻找Y35A进行测试。

**Comment by byteluo** [comment]
关闭模糊效果就行了
