### ISSUE TITLE
您好，小米8跨域消息上方存在空白，应该怎么去掉呢

### ISSUE THREAD

**Issue by byteluo** [kongzue/DialogV3#31]
![Screenshot_2019-07-17-00-51-23-480_com miui home](https://user-images.githubusercontent.com/46063874/61313818-ce523700-a82d-11e9-97d7-4999176712ed.png)

**Comment by kongzue** [comment]
这个我已经注意到此问题，正常的提示显示，需要加入一段顶部距离以规避重叠到状态栏的问题，但在小米8上，MIUI系统额外增加了一段顶部状态栏的距离，导致此问题发生，目前我并不能去掉这段距离，因为这可能在其他设备上出现问题。

**Comment by byteluo** [comment]
谢谢大佬
