### ISSUE TITLE
小米8 跨域通知会改变状态栏颜色 以及上面仁兄提到过的边距问题

### ISSUE THREAD

**Issue by iostyle** [kongzue/DialogV3#33]
<img width="420" alt="image" src="https://user-images.githubusercontent.com/22219146/61626274-6e391600-acaf-11e9-85cd-605f4e0a2ab1.png">
项目写的很棒👍 跨域消息还可以优化一下

**Comment by iostyle** [comment]
<img width="420" alt="image" src="https://user-images.githubusercontent.com/22219146/61626358-b35d4800-acaf-11e9-8ee9-5db08b2965dc.png">

**Comment by kongzue** [comment]
这个我已经注意到此问题，正常的提示显示，需要加入一段顶部距离以规避重叠到状态栏的问题，但在小米8上，MIUI系统额外增加了一段顶部状态栏的距离，导致此问题发生，目前我并不能去掉这段距离，因为这可能在其他设备上出现问题。
