### ISSUE TITLE
ShareDialog只要4个分享类型的时候不能均分底部空间吗

### ISSUE THREAD

**Issue by sceneren** [kongzue/DialogV3#35]
现在默认的位置是5个 只要4个分享类型的时候右边会留很大的空间

**Comment by kongzue** [comment]
您好，我不清楚您在用的是哪种风格。
对于iOS风格，因为是左右滚动的布局结构，无法在小于几个的情况下做平均分布；
对于Kongzue和Material，是表格布局，横纵数量也是定死的，并不能平均分布。
感谢您的建议，很抱歉无法实现您的需求，如果必要，您可以下拉代码自行修改。
