### ISSUE TITLE
文字应该提到strings.xml，方便多语言。

### ISSUE THREAD

**Issue by chenyue404** [kongzue/DialogV3#36]
现在全是中文，还不好改。

**Comment by kongzue** [comment]
您好，文字是根据具体使用在使用方法中定义的，若未定义，该部分，例如取消按钮、消息框的内容等会不显示，不存在默认文本，因此提取到value/string.xml并没有什么意义。

**Comment by chenyue404** [comment]
iOS style, bottomMenu, 传一个数组进去，下面的取消不是默认文本么？就是会显示啊

**Comment by kongzue** [comment]
您好，使用方法：setCancelButtonText(...) 时支持传入String或resId的，您可以使用此方法直接指定您程序中value/string.xml的资源值作为文本引用。
这里之所以不设置成value/string.xml的原因是会默认引用DialogV3库中的com.kongzue.dialog.v3.R.string而并非你的项目中的R.string，所以直接这么做没什么效果，但所有文案您都可以通过方法引用您项目中的String资源。

**Comment by chenyue404** [comment]
感觉我没表达清楚，这样的：
我先初始化
`DialogSettings.style = (DialogSettings.STYLE.STYLE_IOS);`
再调用
`BottomMenu.show((AppCompatActivity) mActivity, new String[]{"1", "2", "3"}, (text, index) -> {
                ToastUtil.show("点击第" + index + "个" + "-" + text);
            });
`
在非中文环境下显示如下：
![20190730112357](https://user-images.githubusercontent.com/5474422/62104440-32ff9e00-b2d2-11e9-9bf3-2998a44fd64d.jpg)
我知道可以setCancelButtonText来修改文字，但是我该如何修改这个“取消”的默认值？

**Comment by kongzue** [comment]
您可以在您的项目中自定义一个value/string.xml：
```
<string name="bottom_cancel">取消</string>
```
并创建其对应的英文：value/string.xml (en)：
```
<string name="bottom_cancel">Cancel</string>
```
然后在您的代码中添加：
```
BottomMenu.show((AppCompatActivity) mActivity, new String[]{"1", "2", "3"}, (text, index) -> { ToastUtil.show("点击第" + index + "个" + "-" + text); }).setCancelButtonText(R.string.bottom_cancel);
```

**Comment by chenyue404** [comment]
这样的话，每次调用都要写一次setCancelButtonText，明显不妥啊。

**Comment by kongzue** [comment]
请使用3.1.0.2测试版本，新增全局设置
```
DialogSettings.defaultCancelButtonText = "取消";
```
可以指定全局默认取消按钮文本，影响BottomDialog和ShareDialog。
您也可以等待后续正式版本更新。

**Comment by chenyue404** [comment]
好的，谢谢。
