### ISSUE TITLE
BottomMenu列表点击没有反应

### ISSUE THREAD

**Issue by HaobinXu** [kongzue/DialogV3#37]
在华为手机上，点击BottomMenu的item没有反应，并且没有显示“取消”按钮

**Comment by kongzue** [comment]
1.请告诉我具体型号；
2.BottomMenu的取消按钮仅在非Material风格时显示，因为Material风格设计规范下，取消是是用下滑手势实现的。

**Comment by kongzue** [comment]
很久没有得到你的回复，我暂时关闭此问题，若您继续需要帮助，可以继续回复我。
