### ISSUE TITLE
DialogHelper leaked

### ISSUE THREAD

**Issue by sichuanyl** [kongzue/DialogV3#38]
DialogHelper leaked 内存泄漏

**Comment by sichuanyl** [comment]
androd.os.HandlerThread.<Java Local>
references android.os.Message.obj
leaks
com.kongzue.dialog.util.DialogHelper instance

**Comment by kongzue** [comment]
![文档截图](https://user-images.githubusercontent.com/10115359/62266652-a8e34100-b45b-11e9-96c6-ce8fbffbd077.png)
