### ISSUE TITLE
oppo手机 消息提醒显示不了？

### ISSUE THREAD

**Issue by bannerkun** [kongzue/DialogV3#39]

**Comment by kongzue** [comment]
请具体描述您使用的组件和调用方法

**Comment by bannerkun** [comment]
感谢即时回复，型号:OPPO R17 系统版本 8.1.0 使用方法: com.kongzue.dialog.v3.Notification.show(
                BaseApplication.INSTANCE.applicationContext, "您有一条新消息", str, R.mipmap.ic_logo
              )
其他手机型号都可以

**Comment by bannerkun** [comment]
其他品牌都没问题

**Comment by kongzue** [comment]
稍后我会抽时间找一台设备进行测试

**Comment by kongzue** [comment]
您好，进过使用云测测试在OPPO R17 with Android 8.1.0上进行所有通知测试，进过测试结果正常。
![info](https://user-images.githubusercontent.com/10115359/62416385-72304500-b66c-11e9-9183-ad58efb78885.png)
以下是测试运行截图：
![1](https://user-images.githubusercontent.com/10115359/62416387-7b211680-b66c-11e9-91af-5ff71d25d23a.png)
![2](https://user-images.githubusercontent.com/10115359/62416389-7ceada00-b66c-11e9-9d58-20fe054f72d5.png)
![3](https://user-images.githubusercontent.com/10115359/62416390-7eb49d80-b66c-11e9-8c57-a4498f61dcef.png)

**Comment by bannerkun** [comment]
有没有试过在后台显示出通知？

**Comment by bannerkun** [comment]
程序在主页面能显示出通知，但是退到后台或者打开另外一个app，就显示不出来了

**Comment by kongzue** [comment]
您好，进过测试，这是OPPO在系统层面上禁止了软件后台弹出界面。
DialogV3的“通知”组件是基于修改Toast实现的，这说明了OPPO禁止App在后台弹出Toast或自定义Toast，而系统设置并不具有“允许显示悬浮窗”之类的选项，这点我们暂时无法解决。
建议在应用处于前台跨Activity的情况下使用DialogV3的“通知”组件，而不是从后台弹出，感谢您的反馈，如果有任何解决方案我会尝试进行修改。

**Comment by bannerkun** [comment]
嗯，谢谢，请教下有什么方案可以在oppo后台弹出吗？

**Comment by bannerkun** [comment]
如果无可以关闭了

**Comment by kongzue** [comment]
这块逐渐的会成为禁区，以后的Android版本也会对后台弹出界面进行更为严格的限制，不建议再研究这块的方式了

**Comment by kongzue** [comment]
据我所知Android Q已经在阻止后台弹出界面了，何况这样的悬浮窗，不过可以研究下用悬浮窗实现，但这样是需要允许悬浮窗权限
