### ISSUE TITLE
底部菜单样式能不能增加类似分享面板的

### ISSUE THREAD

**Issue by sceneren** [kongzue/DialogV3#4]

**Comment by kongzue** [comment]
已列入新需求考虑计划中

**Comment by kongzue** [comment]
请更新至 implementation 'com.kongzue.dialog_v3:dialog:2.9.8.4'
使用方法请参照： https://github.com/kongzue/DialogV3#%E5%88%86%E4%BA%AB%E5%AF%B9%E8%AF%9D%E6%A1%86
