### ISSUE TITLE
BottomMenu 弹框，有时间不显示。

### ISSUE THREAD

**Issue by KnightOneAdmin** [kongzue/DialogV3#42]
华为 mate 10 pro 点弹窗的时候， 有时候不显示 ，不是必现。   调用代码如下 

     RxView.clicks(constraintLayout)
            .throttleFirst(1, TimeUnit.SECONDS)
            .subscribe {
                BottomMenu.show(
                    this@OnLineLoanActivity,
                    arrayOf("个人", "企业")
                ) { text, _ ->
                    tv_loanType.text = "$text"
                    when (text) {
                        "个人" -> {
                            applyType = 1
                        }
                        "企业" -> {
                            applyType = 2
                        }
                    }
                }
            }

**Comment by kongzue** [comment]
您好，我在云测上使用Demo经过每种风格各10次测试，结果为100%弹出成功，目前无法复现您所述的问题，我会继续监控相关反馈。
以下是部分测试截图：

![截屏_2019-08-10_01-06-42](https://user-images.githubusercontent.com/10115359/62796272-6e3c7100-bb0b-11e9-9798-67fb1798644b.png)
![截屏_2019-08-10_01-07-13](https://user-images.githubusercontent.com/10115359/62796273-6e3c7100-bb0b-11e9-831e-f9be6c34d376.png)
![截屏_2019-08-10_01-07-32](https://user-images.githubusercontent.com/10115359/62796275-6ed50780-bb0b-11e9-9fe1-c50f86d30d02.png)
