### ISSUE TITLE
在华为手机上，点击BottomMenu的item没有反应

### ISSUE THREAD

**Issue by byteluo** [kongzue/DialogV3#43]
机型为meta20

**Comment by kongzue** [comment]
您好，进过测试，在华为mate 20 上确实存在使用 Material风格的情况下，菜单list与滑动事件冲突的问题，此问题在其他手机上测试没有发现有问题，可能是华为对系统组件进行修改导致的，目前经过尝试，无法解决此问题（包括不限于将OnTouchListener全部return false也依然无效）。建议您更换其他风格使用。
