### ISSUE TITLE
自定义WaitDialog 然后显示TipDialog 闪退

### ISSUE THREAD

**Issue by sceneren** [kongzue/DialogV3#44]
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.

我自定义了WaitDialog  然后显示 调用接口回调之后 显示TipDialog 提示操作成功。显示TipDialog的时候闪退了

**Comment by kongzue** [comment]
请给出详细的错误日志，目前无法根据你的反馈了解问题在哪里

**Comment by jiaxinjie** [comment]
这个只适合在Activity里面使用吗？在Fragment 不能用？  为什么集成之后就用不了 提示Cannot resolve method

**Comment by jiaxinjie** [comment]
![image](https://user-images.githubusercontent.com/24770231/63205795-471e0a80-c0dc-11e9-8fd1-574bd062adf9.png)
[](url)

**Comment by jiaxinjie** [comment]
这个只适合在Activity里面使用吗？在Fragment 不能用？ 为什么集成之后就用不了 提示Cannot resolve method  
![Uploading image.png…]()

**Comment by jiaxinjie** [comment]
这个只适合在Activity里面使用吗？在Fragment 不能用？ 为什么集成之后就用不了 提示Cannot resolve method
![image](https://user-images.githubusercontent.com/24770231/63205812-92d0b400-c0dc-11e9-8628-1070e76caafa.png)

**Comment by kongzue** [comment]
请强转

**Comment by jiaxinjie** [comment]
好的  谢谢   感谢你的开源
------------------ 原始邮件 ------------------
发件人: "Kongzue"<notifications@github.com>;
发送时间: 2019年8月17日(星期六) 上午10:49
收件人: "kongzue/DialogV3"<DialogV3@noreply.github.com>;
抄送: "_↘袛◎憥慠"<1205242073@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [kongzue/DialogV3] 自定义WaitDialog 然后显示TipDialog 闪退 (#44)




请强转

**Comment by jiaxinjie** [comment]
强转 之后还是用不了 我只是在点击调用
![image](https://user-images.githubusercontent.com/24770231/63205870-679a9480-c0dd-11e9-9dff-f390731113fe.png)

![image](https://user-images.githubusercontent.com/24770231/63205867-58b3e200-c0dd-11e9-8509-4d3150687c83.png)

**Comment by kongzue** [comment]
DialogV3仅支持基于使用AppCompatSupport或者AndroidX库的Android应用程序，如果你直接使用的是extends Activity的构建方法，目前无法支持

**Comment by kongzue** [comment]
因为部分API需要使用AppCompatSupport或者AndroidX库中的方法

**Comment by jiaxinjie** [comment]
好的
