### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by wlxfxy** [kongzue/DialogV3#45]
我这边项目使用autosize进行了屏幕适配，然后在使用messagedialog的时候会出现dialog的右边紧贴着屏幕，导致dialog不能在屏幕中央的情况，请问有没有什么办法能避免这种情况

**Comment by kongzue** [comment]
您好，Kongzue DialogV3是基于DialogFragment实现的，且能够保证在原生模式下完美兼容，如果是用其他屏幕适配方案，请联系方案提供商了解适配方式。

**Comment by wlxfxy** [comment]
请问，能单独为某个dialog设置自定义style吗，我只看到了设置全局的

**Comment by kongzue** [comment]
暂时不支持对dialog单独设置style，目前全局设置主要是为了方便一些特殊需要设计的，例如在电子墨水屏设备上禁止弹窗动画等效果
