### ISSUE TITLE
切换回界面后样式没有了

### ISSUE THREAD

**Issue by yaku2688** [kongzue/DialogV3#48]
用的AndroidX版本，比如调用MessageDialog.show(_mActivity, "提示", “消息", "确定");
然后按Home返回，再切回APP，消息提示框的样式没有了。

**Comment by yaku2688** [comment]
你的示例程序也有这个问题，MessageDialog.show 打开情况下，返回到HOME，再切换后APP，样式没了

**Comment by kongzue** [comment]
您所述的问题不存在。
复现测试机型：1+7Pro，Android P 
![Video_20190902_015533_142](https://user-images.githubusercontent.com/10115359/64093024-5f06b700-cd89-11e9-98ac-5eff3434fa01.gif)
