### ISSUE TITLE
InputDialog长度大于显示长度时，不换行？

### ISSUE THREAD

**Issue by HanGao1** [kongzue/DialogV3#49]
InputDialog长度大于显示长度时，不换行？

**Comment by kongzue** [comment]
经测试不存在您所述的问题。
测试机型：1+7Pro，Android P
![Uploading Screenshot_20190903-154631.jpg…]()

**Comment by kongzue** [comment]
![Screenshot_20190903-154631](https://user-images.githubusercontent.com/10115359/64154065-a9a83200-ce62-11e9-94c8-513e6a3e1962.jpg)

**Comment by night19-cyber** [comment]
输入的，应该是

**Comment by HanGao1** [comment]
能否解决一下呢




------------------ 原始邮件 ------------------
发件人: "night"<notifications@github.com>;
发送时间: 2019年9月4日(星期三) 下午5:54
收件人: "kongzue/DialogV3"<DialogV3@noreply.github.com>;
抄送: "面壁计划"<1002305455@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [kongzue/DialogV3] InputDialog长度大于显示长度时，不换行？ (#49)




输入的，应该是

**Comment by kongzue** [comment]
后续版本会支持输入框换行功能，此需求已加入排期计划，预计一个版本内更新
