### ISSUE TITLE
 protected BOOLEAN cancelable; 等等属性，为什么不把这些属性设为可继承的

### ISSUE THREAD

**Issue by 6324** [kongzue/DialogV3#5]
可继承的话，子类也可以设置是否可关闭，现在只能设置全局的。

**Comment by 6324** [comment]
TipDialog dialog = WaitDialog.build(this);

**Comment by 6324** [comment]
不能

**Comment by kongzue** [comment]
cancelable 本质上是内部属性，用于判断并设置 Dialog 是否可以通过返回键或点击外部区域关闭，它并不是 boolean 类型的，因此不建议外部访问，该属性在各 Dialog 组件中都有 get、set 方法使用 boolean 类型值进行设置，TipDialog 会在未来的版本中加入该属性。

WaitDialog 本质上就是 TipDialog 的代理，他返回的就是 TipDialog。目前 DialogV3 尚处于开发测试阶段，未来的版本将会修改 isShow 的访问权限为 public；

请更换测试版本号为：2.9.8.6，上述的修改已经被应用生效。

**Comment by wwdn** [comment]
自定义的CustomDialog 怎么可以用cancelable来判断，用于判断并设置 Dialog 是否可以通过返回键或点击外部区域关闭？
