### ISSUE TITLE
.Activity.isDestroyed()  出现了几次了 崩溃

### ISSUE THREAD

**Issue by HanGao1** [kongzue/DialogV3#50]
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.app.Activity.isDestroyed()' on a null object reference
        at com.kongzue.dialog.util.BaseDialog.showNext(BaseDialog.java:4)
        at com.kongzue.dialog.util.BaseDialog.showDialog(BaseDialog.java:11)
        at com.kongzue.dialog.v3.MessageDialog.showDialog(MessageDialog.java:7)
        at com.kongzue.dialog.v3.MessageDialog.show(MessageDialog.java:41)

**Comment by kongzue** [comment]
请检查你的Activity句柄是否存在

**Comment by HanGao1** [comment]
我这边就是单纯的调用messagedialog,这个bug偶尔复现




------------------ 原始邮件 ------------------
发件人: "Kongzue"<notifications@github.com>; 
发送时间: 2019年9月5日(星期四) 下午2:45
收件人: "kongzue/DialogV3"<DialogV3@noreply.github.com>; 
抄送: "面壁计划"<1002305455@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [kongzue/DialogV3] .Activity.isDestroyed()  出现了几次了 崩溃 (#50)




请检查你的Activity句柄是否存在

**Comment by kongzue** [comment]
请尝试运行Demo看是否有这个问题，如果问题依然存在，请检查你的设备系统是否存在问题。此组件在各个版本，包含不限于Android7、8、8.1、9、10上都经过已上架的多款软件使用没有遇到你所述的问题

**Comment by Leessy** [comment]
Android7.1.2，也偶尔出现过，抓崩溃日志发现，

**Comment by kongzue** [comment]
@Leessy Activity.isDestroyed()是检测你的Activity是否被回收的语句，此方法系Activity的方法，但Activity是你创建对话框时传入的，**请检查你传入的Activity是不是个null空指针**。目前DialogV3无法支持在一个空指针的Activity上创建对话框。
