### ISSUE TITLE
如何获取软键盘的按键监听？

### ISSUE THREAD

**Issue by adoukei** [kongzue/DialogV3#52]
蓝牙键盘上面的按键监听如何获取到啊  InputDialog.show。之后editDialog.dialog.getDialog()为空， 然后editDialog.getEditTextView().setSelection(s.length()); 也是空。。。。 我改去和获取当前的dialog的按键监听， 点软键盘的确定键的监听在哪里尼

**Comment by kongzue** [comment]
DialogV3有提供onShow监听器：setOnShowListener(listener)，请使用 getEditTextView() 方法获取输入框对象
