### ISSUE TITLE
onTerminate这个方法真机上不会运行的啊

### ISSUE THREAD

**Issue by ycyHub** [kongzue/DialogV3#53]
onTerminate这个方法真机上不会运行的啊，在真机上application结束的时候这个不会运行，那所有未消失的dialog也不会dismiss啊，那又何来的 BaseDialog.unload();方法呢

**Comment by kongzue** [comment]
此方法只是理论上提供一个可以清除所有对话框队列句柄的方法，具体执行策略请根据您的程序来设计。例如在Baseframework框架下的APP，可以使用AppManager中的Activity全局管理监听器来实现当最后一个Activity关闭时执行清除操作。

________________________________
发件人: ycyHub <notifications@github.com>
发送时间: Tuesday, September 17, 2019 4:11:42 PM
收件人: kongzue/DialogV3 <DialogV3@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [kongzue/DialogV3] onTerminate这个方法真机上不会运行的啊 (#53)


onTerminate这个方法真机上不会运行的啊，在真机上application结束的时候这个不会运行，那所有未消失的dialog也不会dismiss啊，那又何来的 BaseDialog.unload();方法呢

―
