### ISSUE TITLE
在4.4机型上出行jni错误

### ISSUE THREAD

**Issue by nxnyk** [kongzue/DialogV3#57]
Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 4267 (om.puwu.rubbish)
错误提示这个，等待提示框和tip提示框都不能用

**Comment by nxnyk** [comment]
![微信图片_20190920155122](https://user-images.githubusercontent.com/42330422/65309416-a3ce8280-dbbe-11e9-9857-72868f3d3997.jpg)

**Comment by kongzue** [comment]
请勿使用androidx版本，或者关闭模糊效果：DialogSettings.isUseBlur = false。根据日志分析，是renderscript的AndroidX版本在您的设备上存在问题，但renderscript库是由Google提供的，我并不能对其进行修改，此问题需要等待Google处理。
