### ISSUE TITLE
自定义布局 无法显示在底部  也无法获取到dialog的返回

### ISSUE THREAD

**Issue by yinking1203** [kongzue/DialogV3#58]
v3版本 希望有自定义的布局 可以显示在底部的属性的API  目前好像没有找到

**Comment by kongzue** [comment]
CustomDialog会在后续版本加入设置屏幕显示位置的方法

**Comment by kongzue** [comment]
请更新至3.1.3版本，参考章节：https://github.com/kongzue/DialogV3#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%AF%B9%E8%AF%9D%E6%A1%86

**Comment by yinking1203** [comment]
Android X 版本仓库是否建设?




------------------ 原始邮件 ------------------
发件人: "notifications"<notifications@github.com>;
发送时间: 2019年10月1日(星期二) 下午3:36
收件人: "kongzue/DialogV3"<DialogV3@noreply.github.com>;
抄送: "尹江峰"<526241452@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [kongzue/DialogV3] 自定义布局 无法显示在底部  也无法获取到dialog的返回 (#58)




请更新至3.1.3版本，参考章节：https://github.com/kongzue/DialogV3#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%AF%B9%E8%AF%9D%E6%A1%86

**Comment by kongzue** [comment]
会更新，但比较慢，因为太忙。

**Comment by yinking1203** [comment]
好吧  希望暂时  没更新 的3.13 与 Android X  不会有影响


------------------ 原始邮件 ------------------
发件人: "notifications"<notifications@github.com>;
发送时间: 2019年10月8日(星期二) 下午2:06
收件人: "kongzue/DialogV3"<DialogV3@noreply.github.com>;
抄送: "尹江峰"<526241452@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [kongzue/DialogV3] 自定义布局 无法显示在底部  也无法获取到dialog的返回 (#58)




会更新，但比较慢，因为太忙。

**Comment by yinking1203** [comment]
我很喜欢您的这个轮子  也希望您能一直优化下去  我也希望这个轮子 越来越好  
  希望下次 自定义的时候  可以 更多的API开放  比如  高度占屏幕自定义  宽度占屏幕自定义  




------------------ 原始邮件 ------------------
发件人: "notifications"<notifications@github.com>;
发送时间: 2019年10月8日(星期二) 下午2:06
收件人: "kongzue/DialogV3"<DialogV3@noreply.github.com>;
抄送: "尹江峰"<526241452@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [kongzue/DialogV3] 自定义布局 无法显示在底部  也无法获取到dialog的返回 (#58)




会更新，但比较慢，因为太忙。
