### ISSUE TITLE
WaitDialog不能根据内容大小自动适应

### ISSUE THREAD

**Issue by m511386374** [kongzue/DialogV3#59]
![65313948-e052ac00-dbc7-11e9-8e53-234cca7f69a0](https://user-images.githubusercontent.com/19544200/65474288-cc4fc880-dead-11e9-960d-f59137513dd1.jpg)
![65313953-e2b50600-dbc7-11e9-86f1-dd16d860af46](https://user-images.githubusercontent.com/19544200/65474296-d07be600-dead-11e9-81e2-380b6bec71fc.png)
![65313950-e183d900-dbc7-11e9-9e62-1c6916ace4ba](https://user-images.githubusercontent.com/19544200/65474297-d245a980-dead-11e9-95f5-76ddef377d9d.png)

**Comment by m511386374** [comment]
![image](https://user-images.githubusercontent.com/19544200/65475043-a841b680-deb0-11e9-9bc2-c535e88294a0.png)

**Comment by kongzue** [comment]
您好，WaitDialog和TipDialog目前仅支持文本根据内容大小自动变化大小，暂不支持图示的大小变化。
