### ISSUE TITLE
不知道该怎么联系大佬！所以在这里提个建议

### ISSUE THREAD

**Issue by STGing** [kongzue/DialogV3#6]
有好多APP有一种弹窗就类似 MessageDialog，但是不一样的是没有 title，目前v3里面如果不设置 title(title的参数传null)，中间的 context 内容的字体还是那么小，而且会自己跑到顶部。如果title传""空字符串，context位置没跑上去，但是还是在靠下的位置没有剧中，而且字体也小。。看了下demo目前好像都没有这种样式的，所以想问下v3有没有这种dialog(看是不是我漏掉了)，如果没有那么建议加一下，我目前碰到的app用这样的还不少。
PS：我当前是用的自定义的方式

**Comment by kongzue** [comment]
你可以title当message用，message传null......
