### ISSUE TITLE
底部选择对话框,对话框布局整体往上移了

### ISSUE THREAD

**Issue by kilo-swodh** [kongzue/DialogV3#64]
![QQ图片20190930102443](https://user-images.githubusercontent.com/16081220/65845425-c99d1980-e36c-11e9-94b4-7d7ddf03fa71.png)

android版本 5.1

`BottomMenu.show(mActivity, new String[]{"文章", "支部"}, new OnMenuItemClickListener() {
                    @Override
                    public void onClick(String text, int index) {
                        switch (index){
                            case 0:
                                type = TYPE_SEARCH_TEXT;
                                mTvType.setText("| 文章");
                                break;
                            case 1:
                                type = TYPE_SEARCH_BRANCH;
                                mTvType.setText("| 支部");
                                break;
                        }
                        mEtSearch.setText("");
                    }
                }).setTitle("请选择搜索类型");`

依赖版本
implementation 'com.kongzue.dialog_v3:dialog:3.1.2'

**Comment by kongzue** [comment]
请检查您的Activity的AppTheme主题是否为AppCompat主题，例如Theme.AppCompat.Light.NoActionBar
