### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.app.Activity.isDestroyed()' on a null object reference

### ISSUE THREAD

**Issue by HanGao1** [kongzue/DialogV3#65]
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.app.Activity.isDestroyed()' on a null object reference

at com.kongzue.dialog.util.BaseDialog.showNext(BaseDialog.java:4)
    at com.kongzue.dialog.util.BaseDialog.showDialog(BaseDialog.java:11)
    at com.kongzue.dialog.v3.MessageDialog.showDialog(MessageDialog.java:7)
    at com.kongzue.dialog.v3.MessageDialog.show(MessageDialog.java:41)
    at com.kongzue.dialog.v3.MessageDialog.show(MessageDialog.java:23)

源码中：protected void showNext() {
        List<BaseDialog> cache = new ArrayList<>();
        cache.addAll(BaseDialog.dialogList);
        for (BaseDialog dialog : cache) {
            if (**dialog.context.get().isDestroyed()**) {
                dialogList.remove(dialog);
            }
        }

在源码中找到 public WeakReference<AppCompatActivity> context; 弱引用导致context为空，望修复

**Comment by kongzue** [comment]
这不是bug。
使用弱引用是为了避免Context句柄被长期持有导致Activity无法被正确gc的问题，一般正常使用是不会遇到此问题的，请检查您的使用逻辑，避免在Activity被gc后执行启动Dialog的情况。

**Comment by oudengding** [comment]
> 这不是错误。
> 使用弱引用是为了避免上下文句柄被长期持有导致活动无法被正确gc的问题，一般正常使用是不会遇到此问题的，请检查您的使用逻辑，避免在活动被gc后执行启动Dialog的情况。

在Activity的销毁阶段调用CustomDialog.unload();可以解决吗？

**Comment by oudengding** [comment]
@kongzue 在Activity的销毁阶段调用CustomDialog.unload();可以避免这个问题吗？

**Comment by kongzue** [comment]
> @kongzue 在Activity的销毁阶段调用CustomDialog.unload();可以避免这个问题吗？

此问题属于开发时传入的Activity是一个null，这并不属于DialogV3本身的问题。请勿使用null作为context启动Dialog。

**Comment by oudengding** [comment]
OK
