### ISSUE TITLE
底部菜单跟那些配置信息有关

### ISSUE THREAD

**Issue by j-gin** [kongzue/DialogV3#67]
Application初始化
![image](https://user-images.githubusercontent.com/23333288/66806075-31e91f00-ef59-11e9-91db-d01244fef53d.png)
dialog显示效果-正常
![image](https://user-images.githubusercontent.com/23333288/66806164-68bf3500-ef59-11e9-8197-f311ab59af58.png)
底部菜单栏显示效果-不正常
![image](https://user-images.githubusercontent.com/23333288/66806205-87bdc700-ef59-11e9-8849-eacb5a94a3db.png)

**Comment by kongzue** [comment]
请检查您的Activity的AppTheme主题是否为AppCompat主题，例如Theme.AppCompat.Light.NoActionBar
