### ISSUE TITLE
后面会出 完全自定义底栏 吗？

### ISSUE THREAD

**Issue by KunMinX** [kongzue/DialogV3#69]
非常喜欢你家的 “完全自定义对话框”，既基于 DialogFragment 的实现从而支持视图控制器重建，又最大程度放开，使得开发者可以使用 DataBinding 来复用圆角资源等。

所以想打听一下，完全自定义底栏，后续会有吗？

**Comment by kongzue** [comment]
会的，在计划内了，预计两个版本内就会出

**Comment by kongzue** [comment]
CustomDialog已经支持设置为底部显示模式，详见文档
