### ISSUE TITLE
自定义布局报错

### ISSUE THREAD

**Issue by shengguan** [kongzue/DialogV3#72]
CustomDialog.show()使用后设置全屏，跟位置都会报错   
![image](https://user-images.githubusercontent.com/8409220/67554530-2f997880-f742-11e9-9f40-d442d1f44d47.png)
![image](https://user-images.githubusercontent.com/8409220/67554570-43dd7580-f742-11e9-8df9-eb8d279ea8eb.png)

**Comment by kongzue** [comment]
请使用最新内测版本3.1.3.12或等待正式版更新
