### ISSUE TITLE
Androidx库在4.4的红米手机上init闪退

### ISSUE THREAD

**Issue by LucasDevelop** [kongzue/DialogV3#73]
Androidx库在4.4的红米手机上init闪退，android的运行没有什么问题。

**Comment by kongzue** [comment]
如果可以请提供崩溃日志，感谢你的反馈

**Comment by LucasDevelop** [comment]
没有输出崩溃日子，应该是内部捕捉了异常，不调用init方法就没问题。

**Comment by kongzue** [comment]
DialogV3不存在内部捕获异常的方法，如果没有任何错误日志请尝试在相同设备上测试Demo看是否存在相同问题，若可以复现，请检查全局Logcat的异常信息，若无法重现，如果可以请提供您启动Dialog 的样本代码我这边尝试下

**Comment by kongzue** [comment]
长时间未收到您的反馈，先关闭此issues，如有疑问可以继续回复
