### ISSUE TITLE
V3版本的BaseDialog中的newContext还是会内存泄露吧？

### ISSUE THREAD

**Issue by ling9400** [kongzue/DialogV3#74]

**Comment by kongzue** [comment]
您好，新版本中，newContext属于弱引用（WeakReference）根据Google的说明：

**Comment by kongzue** [comment]
如果您还有任何疑问欢迎继续留言

**Comment by ling9400** [comment]
我第一次说newContext会泄露是因为我把代码下载到本地了，没注意有更新代码，现在更新之后newContext用了弱引用，是不会有泄露，但好像dialogHelper中的presenter还是有泄露吧？[https://graph.baidu.com/resource/116ab44ce526f541263d201572942253.jpg](url)

**Comment by kongzue** [comment]
这个我会处理下

**Comment by ling9400** [comment]
好的，上面的说明还打错了，应该是DialogHelper中的parent，大概什么时候能处理好呢？我现在也不明白是怎么泄露的，我都没调用任何的对话框都会泄露哦！

**Comment by kongzue** [comment]
这个原因主要还是在Google启动Dialog的时候必须依赖一个Activity导致的，然而往往会出现Activity先于Dialog.dismiss前被结束的情况引发Dialog发生WindowLeaked异常导致程序崩溃，在Google的逻辑下，程序猿应该自行处理好先关闭Dialog后关闭Activity的逻辑。DialogV3在这里自行维护了一条Dialog生成机制以及句柄生命周期判断，避免这种问题发生，但这里就不得不持有了创建Dialog的Activity的Context句柄，实际使用时在结束一个正在显示Dialog的Activity，或者Activity发生“重启“时并不会引发任何错误，然而这里存在一些疏漏，我并没有完全检查Context的回收问题，这些问题会在之后的版本更新中修复。

**Comment by kongzue** [comment]
下一个正式版更新日期不确定，但测试版本我会在今晚（最迟明天）发布一个新的修订版本，会通知你更新。

**Comment by ling9400** [comment]
好的

**Comment by kongzue** [comment]
如果您正在使用Support版本请更新至3.1.4.2测试版本，如果正在使用AndroidX版本请等待正式版本更新，如果还有疑问可以继续给我留言。
