### ISSUE TITLE
华为手机按home键上划在任务管理,让后在点击回到屏幕会出现进度条消失,再重复之前步骤又好了

### ISSUE THREAD

**Issue by lijore** [kongzue/DialogV3#77]

**Comment by kongzue** [comment]
DialogV3没有进度条功能啊......

**Comment by lijore** [comment]
华为  HONOR 9X PRO

**Comment by kongzue** [comment]
已复现此问题，正在着手解决

**Comment by lijore** [comment]
好的辛苦解决下，其实我项目中挺急的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xiaoxiaohaozai"<notifications@github.com&gt;; 
发送时间: 2019年10月31日(星期四) 晚上6:06
收件人: "kongzue/DialogV3"<DialogV3@noreply.github.com&gt;; 
抄送: "李强"<446528285@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [kongzue/DialogV3] 华为手机按home键上划在任务管理,让后在点击回到屏幕会出现进度条消失,再重复之前步骤又好了 (#77)




已复现此问题，正在着手解决

**Comment by kongzue** [comment]
因原生ProgressView无法实现线条粗细的控制，这个等待提示布局是基于开源的 ProgressView@Github: https://github.com/Runly/CircularProgressView 来实现的，但他本身就存在此问题，建议先使用setCustomView(...)使用自定义的ProgressView来替换此组件

**Comment by lijore** [comment]
没关系可以等你修复




            
            
                
                    
                            
                                
                            
                            
                                446528285
                            
                    
                        
                            
                                    邮箱：446528285@qq.com
                            
                        
                
            
        Signature is customized by Netease Mail Master


在2019年10月31日 18:11，Kongzue 写道： 因原生ProgressView无法实现线条粗细的控制，这个等待提示布局是基于开源的 ProgressView@Github: https://github.com/Runly/CircularProgressView 来实现的，但他本身就存在此问题，建议先使用setCustomView(...)使用自定义的ProgressView来替换此组件

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/kongzue/DialogV3/issues/77?email_source=notifications\u0026email_token=AESPM4P43LAFCKVR24IDRILQRKVMVA5CNFSM4JHG2ZX2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECXGAWY#issuecomment-548298843",
"url": "https://github.com/kongzue/DialogV3/issues/77?email_source=notifications\u0026email_token=AESPM4P43LAFCKVR24IDRILQRKVMVA5CNFSM4JHG2ZX2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECXGAWY#issuecomment-548298843",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by kongzue** [comment]
如果您正在使用support版本，请更新至测试版本 3.1.4.1 或等待正式版本，已完成修复，我更换了 ProgressView 的实现组件，此问题不会再出现。如果使用AndroidX版本请等待正式版本更新。

**Comment by lijore** [comment]
依赖是报错麻烦看下&nbsp; &nbsp;
ERROR: Unable to resolve dependency for ':app@release/compileClasspath': Could not download dialog.aar (com.kongzue.dialog_v3:dialog:3.1.4.1)




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xiaoxiaohaozai"<notifications@github.com&gt;; 
发送时间: 2019年10月31日(星期四) 晚上6:37
收件人: "kongzue/DialogV3"<DialogV3@noreply.github.com&gt;; 
抄送: "李强"<446528285@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [kongzue/DialogV3] 华为手机按home键上划在任务管理,让后在点击回到屏幕会出现进度条消失,再重复之前步骤又好了 (#77)




如果您正在使用support版本，请更新至测试版本 3.1.4.1 或等待正式版本，已完成修复，我更换了 ProgressView 的实现组件，此问题不会再出现。如果使用AndroidX版本请等待正式版本更新。

**Comment by kongzue** [comment]
已检查，3.1.4.1已经上传成功：https://bintray.com/myzchh/maven/dialogV3/3.1.4.1#files/com%2Fkongzue%2Fdialog_v3%2Fdialog%2F3.1.4.1 如果您引入出现问题，请检查您的网络
