### ISSUE TITLE
oppo 手机   Android 8.1  出现异常崩溃 

### ISSUE THREAD

**Issue by yinking1203** [kongzue/DialogV3#79]
回退仓库版本 也不行   
项目
 minSdkVersion 17
 targetSdkVersion 29

![QQ截图20191105142606](https://user-images.githubusercontent.com/23116465/68184246-79ebe680-ffd9-11e9-9487-0e543f7c76e1.png)

**Comment by kongzue** [comment]
请勿对DialogV3进行混淆。详情请查看https://github.com/kongzue/DialogV3#%E6%B7%B7%E6%B7%86%E8%AE%BE%E7%BD%AE
