### ISSUE TITLE
Error in WaitDialog 

### ISSUE THREAD

**Issue by dondeepak** [kongzue/DialogV3#8]
Even after WaitDialog.dismiss() WaitDialog still shows and its with text of "tip "in it please tell me how to fix it

**Comment by kongzue** [comment]
Normally this problem should not occur unless the handle changes in the context, or the handle in the BaseDialog.dialogList is abnormal.

**Comment by zhangchaoxu** [comment]
I have the same issue in TipDialog

**Comment by dondeepak** [comment]
@kongzue  so how do i solve this??

**Comment by kongzue** [comment]
You can try beta version 3.0.1.1, I am trying to find the cause of the problem.

________________________________
发件人: dondeepak <notifications@github.com>
发送时间: Thursday, May 23, 2019 11:04:30 PM
收件人: kongzue/DialogV3
抄送: Kongzue; Mention
主题: Re: [kongzue/DialogV3] Error in WaitDialog (#8)


@kongzue<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkongzue&data=02%7C01%7C%7C7ac195e92a90485fe90808d6df8ff615%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636942206727114159&sdata=gpVnV4c2lQFAVmVSYOyd2CGNKMJ1gU8DbT%2BLrG8bI1o%3D&reserved=0> so how do i solve this??

―

**Comment by kongzue** [comment]
Please update to version 3.0.2 to fix this problem.
