### ISSUE TITLE
More than one file was found with OS independent path ‘lib/armeabi-v7a/libRSSupport.so’

### ISSUE THREAD

**Issue by longzekai** [kongzue/DialogV3#81]
集成到项目之后，每次编译都会报这个错误。

**Comment by kongzue** [comment]
请尝试Demo是否能正常运行，如果可以，请检查您的项目是否已按照文档配置renderscript，若已配置，请检查您的项目已集成的其他库是否有使用renderscript其他版本。
另外，可以通过以下代码检查renderscript兼容性，请在软件启动时执行：
DialogSettings.checkRenderscriptSupport(context);

**Comment by kongzue** [comment]
暂时无法提供更多帮助，我先关闭此问题，如遇到解决方案我会告诉您

**Comment by creativityingenuity** [comment]
我集成也报这个错
