### ISSUE TITLE
CustomDialog  setFullScreen方法失效  小米Android9 无法全屏宽高

### ISSUE THREAD

**Issue by yinking1203** [kongzue/DialogV3#82]
![1](https://user-images.githubusercontent.com/23116465/68582490-d48fb180-04b5-11ea-96cb-4544f50559d9.png)
![2](https://user-images.githubusercontent.com/23116465/68582496-d8233880-04b5-11ea-8204-aec09a55373e.png)

**Comment by kongzue** [comment]
您好，设置Align后默认就是FullScreen的，无需额外设置，且开启Align后不再支持非FullScreen显示，要设置边距请自行设置margin。

**Comment by yinking1203** [comment]
&nbsp;不管是设置Align后默认的FullScreen &nbsp;还是手动设置FullScreen &nbsp;高度始终不能够全屏哦




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"notifications"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月12日(星期二) 凌晨0:19
收件人:&nbsp;"kongzue/DialogV3"<DialogV3@noreply.github.com&gt;;
抄送:&nbsp;"尹江峰"<526241452@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kongzue/DialogV3] CustomDialog  setFullScreen方法失效  小米Android9 无法全屏宽高 (#82)




您好，设置Align后默认就是FullScreen的，无需额外设置，且开启Align后不再支持非FullScreen显示，要设置边距请自行设置margin。

**Comment by kongzue** [comment]
您好，您所说的高度可能是因为顶部状态栏和已隐藏掉的底部导航栏所构成的“安全区”导致的，此问题我做过研究是无法避免的（类似问题：https://www.jianshu.com/p/6bf0d6b6707a）如果要使用完全全屏的界面建议使用Activity实现。

**Comment by kongzue** [comment]
您好，请尝试在最新版本中尝试以下代码：
```
CustomDialog.build(me, R.layout.layout_custom_dialog, new CustomDialog.OnBindView() {
    @Override
    public void onBind(final CustomDialog dialog, View v) {
       
    }
}).setOnShowListener(new OnShowListener() {
    @Override
    public void onShow(BaseDialog baseDialog) {
        //重点：
        Dialog dialog = baseDialog.dialog.get().getDialog();
        dialog.getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN);
        WindowManager.LayoutParams lp = dialog.getWindow().getAttributes();
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
            lp.layoutInDisplayCutoutMode = WindowManager.LayoutParams.LAYOUT_IN_DISPLAY_CUTOUT_MODE_SHORT_EDGES;
        }
        dialog.getWindow().setAttributes(lp);
    }
}).show();
```

**Comment by kongzue** [comment]
长时间未收到您的回复，暂时关闭此问题，如有需要可以继续回复
