### ISSUE TITLE
TextInfo fontSize单位问题

### ISSUE THREAD

**Issue by qiushui95** [kongzue/DialogV3#84]
单位默认是dp  能否改成px  或者设置的时候传单位进来。
我的项目主要单位是pt ，设置之后适配不合适。

**Comment by kongzue** [comment]
您好，暂不支持px，您可以使用以下代码来进行px至dp的转换：
public static int px2dip(Context context, float pxValue) {
        final float scale = context.getResources().getDisplayMetrics().density;
        return (int) (pxValue / scale + 0.5f);
}

**Comment by qiushui95** [comment]
@kongzue 有没有计划支持px

**Comment by kongzue** [comment]
没有，目前也不能对现有的适配方式进行修改。px适配可能导致在不同分辨率（例如1080p和2k）下出现严重的比例不和谐问题，而布局和文字都适用dp则近乎是等比例的，不会有这些问题，所以目前DialogV3只会支持dp作为适配单位进行设置。
