### ISSUE TITLE
点击无反应，将lib压成aar使用，没有任何初始化

### ISSUE THREAD

**Issue by printlybyte** [kongzue/DialogV3#85]
List<ShareDialog.Item> itemList = new ArrayList<>();
                itemList.add(new ShareDialog.Item(HuodongActivityDetails.this, R.mipmap.ic_app_log, "知里好友"));
                itemList.add(new ShareDialog.Item(HuodongActivityDetails.this, R.mipmap.img_qq_material, "QQ"));
                itemList.add(new ShareDialog.Item(HuodongActivityDetails.this, R.mipmap.img_wechat_material, "微信"));
                itemList.add(new ShareDialog.Item(HuodongActivityDetails.this, R.mipmap.img_wechat_friends_material, "朋友圈"));
                itemList.add(new ShareDialog.Item(HuodongActivityDetails.this, R.mipmap.ic_share_wechat_jietu, "微信快照"));
                itemList.add(new ShareDialog.Item(HuodongActivityDetails.this, R.mipmap.ic_share_wefriends, "朋友圈快照"));
                ShareDialog.show(HuodongActivityDetails.this, itemList, new ShareDialog.OnItemClickListener() {

                    @Override

                    public boolean onClick(ShareDialog shareDialog, int index, ShareDialog.Item item) {

**Comment by kongzue** [comment]
您好，请尝试Demo在您的设备上是否正常运行，如果也存在相同问题请告知您的设备型号我这边会进行复测，如果未出现问题请检查您的编译环境、Context句柄是否处于活动状态。

**Comment by kongzue** [comment]
长时间未收到您的回复，暂时关闭此问题，如有疑问可继续回复。
