### ISSUE TITLE
内存泄漏问题

### ISSUE THREAD

**Issue by weibindev** [kongzue/DialogV3#86]
我将WaitDialog封装在RxJava的线程调度中，然后再BaseActivity里的onDestroy()执行BaseDialog.unload()还是会内存泄漏
```kotlin
fun <T> applyConvertWithDialog(
        activity: AppCompatActivity,
        content: String?
    ): ObservableTransformer<ApiResult<T>, T> {
        return ObservableTransformer { upstream ->

            upstream.subscribeOn(Schedulers.io())
                .doOnSubscribe {
                    WaitDialog.show(activity, content)
                }
                .subscribeOn(AndroidSchedulers.mainThread())
                .observeOn(AndroidSchedulers.mainThread())
                .doFinally {
                    WaitDialog.dismiss()
                }.compose(convert())
        }
    }
```

Leaks检测到内存泄漏信息

LibraryLeak(className=com.kongzue.dialog.util.DialogHelper, leakTrace=
┬
├─ android.net.ConnectivityThread
│    Leaking: UNKNOWN
│    Thread name: 'ConnectivityThread'
│    GC Root: Java local variable
│    ↓ thread ConnectivityThread.<Java Local>
│                                ~~~~~~~~~~~~
├─ android.os.Message
│    Leaking: UNKNOWN
│    ↓ Message.obj
│              ~~~
╰→ com.kongzue.dialog.util.DialogHelper
​     Leaking: YES (Fragment#mFragmentManager is null and ObjectWatcher was watching this)
​     key = 830a8260-26f6-4aa6-8200-4c98a8e0c814
​     watchDurationMillis = 8231
​     retainedDurationMillis = 3218
, retainedHeapByteSize=120032, pattern=instance field android.os.Message#obj, description=A thread waiting on a blocking queue will leak the last dequeued object as a stack local reference. So when a HandlerThread becomes idle, it keeps a local reference to the last message it received. That message then gets recycled and can be used again. As long as all messages are recycled after being used, this won't be a problem, because these references are cleared when being recycled. However, dialogs create template Message instances to be copied when a message needs to be sent. These Message templates holds references to the dialog listeners, which most likely leads to holding a reference onto the activity in some way. Dialogs never recycle their template Message, assuming these Message instances will get GCed when the dialog is GCed. The combination of these two things creates a high potential for memory leaks as soon as you use dialogs. These memory leaks might be temporary, but some handler threads sleep for a long time. To fix this, you could post empty messages to the idle handler threads from time to time. This won't be easy because you cannot access all handler threads, but a library that is widely used should consider doing this for its own handler threads. This leaks has been shown to happen in both Dalvik and ART.)

**Comment by weibindev** [comment]
使用版本 api 'com.kongzue.dialog_v3x:dialog:3.1.5'

**Comment by kongzue** [comment]
请检查 BaseDialog.unload() 执行后是否有正确对内存gc，如果已 gc内存仍有泄漏，请告知泄露点位置。
目前 DialogV3 中，因采用模态化显示方式，会对未显示的Dialog进行缓存处理，context句柄也做了对应的WeakReference处理，理论上不存在无法回收的情况。

**Comment by weibindev** [comment]
┬
├─ android.os.HandlerThread
│    Leaking: UNKNOWN
│    Thread name: 'queued-work-looper'
│    GC Root: Java local variable
│    ↓ thread HandlerThread.<Java Local>
│                           ~~~~~~~~~~~~
├─ android.os.Message
│    Leaking: UNKNOWN
│    ↓ Message.obj
│              ~~~
╰→ com.kongzue.dialog.util.DialogHelper
​     Leaking: YES (Fragment#mFragmentManager is null and ObjectWatcher was watching this)
​     key = c8ecd188-a616-41af-8478-3b72c71aa8b4
​     watchDurationMillis = 45027
​     retainedDurationMillis = 40025
, retainedHeapByteSize=0, pattern=instance field android.os.Message#obj, description=A thread waiting on a blocking queue will leak the last dequeued object as a stack local reference. So when a HandlerThread becomes idle, it keeps a local reference to the last message it received. That message then gets recycled and can be used again. As long as all messages are recycled after being used, this won't be a problem, because these references are cleared when being recycled. However, dialogs create template Message instances to be copied when a message needs to be sent. These Message templates holds references to the dialog listeners, which most likely leads to holding a reference onto the activity in some way. Dialogs never recycle their template Message, assuming these Message instances will get GCed when the dialog is GCed. The combination of these two things creates a high potential for memory leaks as soon as you use dialogs. These memory leaks might be temporary, but some handler threads sleep for a long time. To fix this, you could post empty messages to the idle handler threads from time to time. This won't be easy because you cannot access all handler threads, but a library that is widely used should consider doing this for its own handler threads. This leaks has been shown to happen in both Dalvik and ART.)])

**Comment by kongzue** [comment]
您好，未查询到DialogHelper中有对象mFragmentManager，且所有DialogHelper的句柄也都被WeakReference处理，如果您还有疑问可以查看源代码：https://github.com/kongzue/DialogV3/blob/master/dialog/src/main/java/com/kongzue/dialog/util/DialogHelper.java

**Comment by weibindev** [comment]
会不会是DialogFragment的dialog的变量Handler对DialogFragment持有导致的？
```
Dialog(@NonNull Context context, @StyleRes int themeResId, boolean createContextThemeWrapper) {
        if (createContextThemeWrapper) {
            if (themeResId == ResourceId.ID_NULL) {
                final TypedValue outValue = new TypedValue();
                context.getTheme().resolveAttribute(R.attr.dialogTheme, outValue, true);
                themeResId = outValue.resourceId;
            }
            mContext = new ContextThemeWrapper(context, themeResId);
        } else {
            mContext = context;
        }

        mWindowManager = (WindowManager) context.getSystemService(Context.WINDOW_SERVICE);

        final Window w = new PhoneWindow(mContext);
        mWindow = w;
        w.setCallback(this);
        w.setOnWindowDismissedCallback(this);
        w.setOnWindowSwipeDismissedCallback(() -> {
            if (mCancelable) {
                cancel();
            }
        });
        w.setWindowManager(mWindowManager, null, null);
        w.setGravity(Gravity.CENTER);

        mListenersHandler = new ListenersHandler(this);
    }
```

**Comment by kongzue** [comment]
查证了下，DialogHelper里是没有其他可能导致内存泄露的句柄存在的，且DialogHelper是DialogFragment的实现，拥有自己的生命周期，如果是DialogFragment里的变量，那么只能由Google进行处理了，目前我没有什么好的办法。

**Comment by weibindev** [comment]
好吧，还是非常感谢作者能作出效果这么不错的库的
