### ISSUE TITLE
运行崩溃问题

### ISSUE THREAD

**Issue by 18856914956** [kongzue/DialogV3#88]
一旦在MainActivity中加入预先设置（DialogSettings相关设置checkRenderscriptSupport），运行APP，就会崩溃

去除DialogSettings相关设置checkRenderscriptSupport后，显示对话框时程序异常

 A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 5398

InputDispatcher: channel '2a2875e0 XXX (server)' ~ Channel is unrecoverably broken and will be disposed!

**Comment by kongzue** [comment]
请提供崩溃日志。
另外您给出的日志信息应该跟推送管道有关，DialogV3并未吊用任何推送管道

**Comment by kongzue** [comment]
长时间未收到您的回复，我先关闭此issues，如有任何疑问可以继续回复

**Comment by protectedMan** [comment]
vivo x7 5.1.1 系统也出现了此问题。Fatal signal 11  ，DIalogV3版本是3.1.8
经过测试是因为 调用 checkRenderscriptSupport造成的。

**Comment by kongzue** [comment]
@protectedMan 应该是系统存在问题，我这边无法提供任何帮助，请使用方法：DialogSettings.isUseBlur = false; 关闭模糊效果
