### ISSUE TITLE
在dialog消失的时候会报空指针异常

### ISSUE THREAD

**Issue by zhangchaoxu** [kongzue/DialogV3#9]
报空指针
`
java.lang.NullPointerException         at com.kongzue.dialog.v3.TipDialog.access$000(TipDialog.java:34)         at com.kongzue.dialog.v3.TipDialog$3.onDismiss(TipDialog.java:149)         at com.kongzue.dialog.util.BaseDialog$1.onDismiss(BaseDialog.java:109)         at com.kongzue.dialog.util.DialogHelper.onDismiss(DialogHelper.java:172)         at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1238)         at android.os.Handler.dispatchMessage(Handler.java:102)         at android.os.Looper.loop(Looper.java:136)         at android.app.ActivityThread.main(ActivityThread.java:5017)         at java.lang.reflect.Method.invokeNative(Native Method)         at java.lang.reflect.Method.invoke(Method.java:515)         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)         at dalvik.system.NativeStart.main(Native Method)
`

**Comment by kongzue** [comment]
您是否在 BaseDialog.unload(); 后启动TipDialog？
正常情况下 waitDialogTemp 是不可能为 null 的，因为在该代码（TipDialog.java:149）执行前会执行 build(...) 方法创建 waitDialogTemp

**Comment by zhangchaoxu** [comment]
我没有主动执行过BaseDialog.unload()操作，不知道是不是其它操作引起过这个的执行

**Comment by kongzue** [comment]
主要是没道理出现这问题啊，你可以看代码，TipDialog.java:149之前肯定会执行build，那么waitDialogTemp不可能为空

**Comment by zhangchaoxu** [comment]
是的，所以说很奇怪，我昨天升级到了v3
主要遇到这么几个问题
1. 上面的空指针异常
2. TipDialog不会主动消失，一直显示在页面上
3. 没找到地方可以自定义WaitDialog的TextInfo

**Comment by kongzue** [comment]
您想尝试下测试版：3.0.1.1
加了几个null判断以及TipDialog和WaitDialog增加setMessageTextInfo(...);

**Comment by zhangchaoxu** [comment]
谢谢，我试一下

**Comment by kongzue** [comment]
麻烦问下是否还存在此问题

**Comment by kongzue** [comment]
问题我先关掉了，如果还存在麻烦再开启提交
