### ISSUE TITLE
能支持哈返回键事件的拦截吗

### ISSUE THREAD

**Issue by cc365774016** [kongzue/DialogV3#90]

**Comment by kongzue** [comment]
不能，目前只能设置不允许返回关闭

**Comment by cc365774016** [comment]
有办法能实现吗，不能的话，只能在activity每次去拦截，判断窗口是否在显示了

**Comment by kongzue** [comment]
这不属于普遍需求，除非你有特别强烈的需求用途，请描述给我，否则我不能为此添加这个功能

**Comment by cc365774016** [comment]
比如在一些重要的，比如和蓝牙设备通信的过程中，显示了一个waitdialog，用户可能想点击返回键退出页面，这个时候需要一个messagedialog提示用户是否中断。

**Comment by cc365774016** [comment]
很多一些第三方的dialog，popup继承自定义view来实现的，都提供了拦截返回键的监听，这个需求应该还是比较普片的吧

**Comment by cc365774016** [comment]
我之前用的那个xpopup就提供了拦截返回键，但是由于那个框架有一个重大缺陷，不能在activity非可见的时候去创建。

**Comment by kongzue** [comment]
DialogV3也不能在activity非可见情况下创建啊

**Comment by cc365774016** [comment]
我测试过，activity在home键后，是可以创建的啊

**Comment by kongzue** [comment]
但并不能显示，dialog是依赖于activity去显示的，并不能独立显示，这是Google的限制，不是想不想做的问题

**Comment by cc365774016** [comment]
activity必须要依赖的，我的意思是，当我在activity页面，然后按下home键，hander一个延时5秒的消息，当10秒后，我回到页面，之前在home后台的时间里显示的那个dialog是可以显示出来的

**Comment by cc365774016** [comment]
我实际用你的demo测试过，是可以的。

**Comment by kongzue** [comment]
我以为你说的是在后台显示...

**Comment by kongzue** [comment]
另外我查了下，DialogFragment天生没有onKey事件，目前我没法对此问题提供帮助
![Snipaste_2019-11-15_15-22-56](https://user-images.githubusercontent.com/10115359/68924446-d14d3c00-07bb-11ea-8db6-480616f4ffe8.png)

**Comment by cc365774016** [comment]
嗯。所以目前只能通过activity去拦截判断当前dialog是否显示了。

**Comment by kongzue** [comment]
我再查查看

**Comment by cc365774016** [comment]
谢谢大大的回复

**Comment by kongzue** [comment]
找到办法了...你可以试试在onShowListener里，使用:
dialog.setOnKeyListener(new DialogInterface.OnKeyListener() {
            @Override
            public boolean onKey(DialogInterface dialog, int keyCode, KeyEvent event) {
                return false;
            }
});

**Comment by kongzue** [comment]
if (keyCode == KeyEvent.KEYCODE_BACK) {
    //你的事务
    return true;
}

**Comment by cc365774016** [comment]
好的，谢谢。大大也可以把这个的用法写到说明里，给后面的小伙伴看看

**Comment by kongzue** [comment]
这个我会想办法封装下接口的，稍后通知你更新内测版本

**Comment by kongzue** [comment]
如果你正在使用Support版本，请更新至3.1.5.2测试版本，如果你正在使用Android X版本请等待正式版本更新。以下是更新日志：
Dialog（消息、输入、底部菜单、分享、等待、提示、自定义对话框）新增setOnBackClickListener(...)方法可设置返回按钮监听。该监听器会return一个boolean值用于判断是否拦截此返回事件而不继续执行对话框dismiss事件。

**Comment by cc365774016** [comment]
android X版本我用一个新的工程都下载不下来，用的阿里云的镜像仓库，jecnter()也试过，都不行

**Comment by kongzue** [comment]
网络问题，我这边引包没任何问题，请自行梯子即可

**Comment by kongzue** [comment]
讨论群：271127803

**Comment by kongzue** [comment]
已更新正式版 3.1.6
