### ISSUE TITLE
可以禁止表单表情符输入吗

### ISSUE THREAD

**Issue by bingely** [kongzue/DialogV3#91]
这个功能很常用，因为输入框输入表情符提交给服务器，一般是不支持的

**Comment by kongzue** [comment]
其实吧，这问题我们项目也有遇到，主要问题倒不是不支持，大概率是MySQL的字符集没设置对，要使用unicode是绝对不会有问题的，你也可以和后台商量下实在不行base64处理下嘛不要偷懒XD
好吧说正事，输入对话框提供了自定义类：DialogSettings.inputInfo 你可以通过全局设置设置它，它包含了.setInputType(InputType) 方法可以设置限制输入类型，您可以在这里限制android提供的文本类型，详见系统InputType类与文档。

**Comment by kongzue** [comment]
如果没有其他问题我先关闭此issues了，如果有可以继续留言

**Comment by bingely** [comment]
谢谢回复。
“.setInputType(InputType) 方法可以设置限制输入类型” 
，你设置了文本类型或者密码类型，照样可以输表情符
