### ISSUE TITLE
点击外部消失和点击返回键消失。能否分成两个方法分别设置，而不是只能统一设置两个

### ISSUE THREAD

**Issue by cc365774016** [kongzue/DialogV3#92]

**Comment by kongzue** [comment]
可以。
请更新至测试版本3.1.5.5或等待正式版本。
“点击返回”设置你可以使用setOnBackClickListener(onBackClickListener)中return true或false来决定Dialog是否关闭。
“点击外部消失”你可以通过设置setCancelable(boolean)来决定是否关闭对话框。

**Comment by cc365774016** [comment]
androidX还没有3.1.5.5

**Comment by kongzue** [comment]
请等待正式版更新，预计两天内

**Comment by cc365774016** [comment]
好的

**Comment by cc365774016** [comment]
麻烦大佬通过哈我的加群请求。我QQ号365774016

**Comment by kongzue** [comment]
我这边没有自己的群，那个群我也不是群主，只是管理，我直接拉你进去吧

**Comment by kongzue** [comment]
已更新正式版 3.1.6
