### ISSUE TITLE
V2包和V3包不能共存吗？

### ISSUE THREAD

**Issue by protectedMan** [kongzue/DialogV3#94]
![image](https://user-images.githubusercontent.com/17565737/69294092-d8ee6400-0c45-11ea-837c-aa8eee81ab42.png)

**Comment by kongzue** [comment]
建议升级至V3，升级注意事项详见 https://github.com/kongzue/DialogV3/blob/master/kongzue_dialog_v2_upto_v3.md

**Comment by protectedMan** [comment]
我现在项目里大量使用v2的包内容，如果不能共存的话我需要修改大量代码！

**Comment by kongzue** [comment]
这个我也很无奈，V3库之所以作为独立的库进行发布的主要原因也是其API发生了较大变动，而我个人又无力同时维护多个库版本的更新，因此目前主要更新V3的库。V3库相比V2主要是API上的更新以及Pop被取消，如果实在是太麻烦或者不得不使用Pop建议不要更新，否则还是建议尽早升级至V3
