### ISSUE TITLE
空指针

### ISSUE THREAD

**Issue by Andy957** [kongzue/DialogV3#95]
#9003 java.lang.NullPointerException
Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference

com.kongzue.dialog.util.view.BlurView.<init>(BlurView.java:58)

**Comment by kongzue** [comment]
收到

**Comment by Andy957** [comment]
#8103 java.lang.NoSuchMethodError
android.support.v7.app.AppCompatActivity.isDestroyed
com.kongzue.dialog.util.BaseDialog.showNow(BaseDialog.java:171)

还有这个问题
![image](https://user-images.githubusercontent.com/52651185/69304616-38576e80-0c5c-11ea-9576-a506f8be1b2f.png)
如果是系统版本的问题那就不管他了

**Comment by kongzue** [comment]
有可能，目前库的兼容最低版本是API-17

**Comment by Andy957** [comment]
老哥这个库有点大，添加进去以后安装包大了1m

**Comment by kongzue** [comment]
没办法啊一堆图，资源就一大堆

**Comment by kongzue** [comment]
暂时关闭此问题，如有疑问可继续留言。
