### ISSUE TITLE
自定义的WaitDialog显示中调用TipDialog的show()出现闪退

### ISSUE THREAD

**Issue by sceneren** [kongzue/DialogV3#96]
//自定义WaitDialog
```
fun showWaitDialog(activity: AppCompatActivity, msg: String?) {
        try {
            WaitDialog.show(activity, if (msg.isNullOrEmpty()) "加载中..." else msg).setCustomView(
                R.layout.wait_dialog_custom_view
            ) { _, v ->
                val animView = v?.findViewById<ImageView>(R.id.animView)
                animView.let {
                    animView!!.post {
                        animView.setImageResource(R.drawable.ic_wait_dialog_new_anim)
                        if (animView.drawable is AnimationDrawable) {
                            val animDraw = animView.drawable as AnimationDrawable
                            animDraw.start()
                        }
                    }
                }
            }
                .setBackgroundResId(R.drawable.bg_custom_dialog)
                .theme = DialogSettings.THEME.DARK
        } catch (e: Exception) {
            e.printStackTrace()
        }

    }
```

在调用showWaitDialog()之后，执行
```
TipDialog.show(
                                this@MatchDetailActivity,
                                "操作失败请重试",
                                TipDialog.TYPE.ERROR
                            )
```
出现：
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
    at android.view.ViewGroup.addViewInner(ViewGroup.java:5106)
    at android.view.ViewGroup.addView(ViewGroup.java:4935)
    at android.view.ViewGroup.addView(ViewGroup.java:4875)
    at android.view.ViewGroup.addView(ViewGroup.java:4848)
    at com.kongzue.dialog.v3.TipDialog.refreshView(TipDialog.java:362)
    at com.kongzue.dialog.v3.TipDialog.setTip(TipDialog.java:460)
    at com.kongzue.dialog.v3.TipDialog.show(TipDialog.java:163)

自定义的布局文件
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:orientation="vertical">

    <ImageView
        android:id="@+id/animView"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:src="@drawable/ic_wait_dialog_new_anim" />
</LinearLayout>
```

**Comment by kongzue** [comment]
请确认您在使用最新版本，未在TipDialog.java:362行找到您所描述的信息

**Comment by sceneren** [comment]
<img width="796" alt="WX20191126-095704@2x" src="https://user-images.githubusercontent.com/6612998/69593086-20ecfc80-1033-11ea-83ae-30e3d8e57861.png">
这一行

**Comment by kongzue** [comment]
收到,这个会在新版本中处理

**Comment by kongzue** [comment]
若果你正在使用Support版本，请更新至3.1.6.2测试版本，如果你使用AndroidX版本，需要等待后续正式版更新。

**Comment by wangrui460** [comment]
同样的问题，出现在 CustomDialog中，更新到 3.1.6.2 问题依然在

**Comment by kongzue** [comment]
您好，因疫情原因暂未复工，您的反馈已经收到，我会尽快处理。

**Comment by creativityingenuity** [comment]
v3x:dialog:3.2.4.1 还有啊

**Comment by kongzue** [comment]
@creativityingenuity 请更新至最新版本以修复此问题：3.2.5
更推荐尽快迁移至[DialogX](https://github.com/kongzue/DialogX)，V3将在不久停止更新。
