### ISSUE TITLE
Change the color of the FullScreenDialog title bar

### ISSUE THREAD

**Issue by taksumaki** [kongzue/DialogV3#97]
How to change the color of the title bar using FullScreenDialog? I don't want to have the white bar, if not black.

I already tried putting the subject in Dark but it remains the same.

**Comment by kongzue** [comment]
FullScreenDialog does not support night mode for the time being, but it will be supported in future versions. and more customizable options will be provided. 
I will reply to you here after the new version is released.

**Comment by taksumaki** [comment]
I hope it is soon because I need it and for the setTheme() option to work. :)

**Comment by kongzue** [comment]
There is good news to that can be confirmed is that the next version will add the dark mode of BottomMenu and FullScreenDialog, and FullScreenDialog will also support custom background colors.

**Comment by kongzue** [comment]
It is expected that you can update to a beta support version in two days.

**Comment by taksumaki** [comment]
I will look forward to the new version. :)

**Comment by kongzue** [comment]
This is preview picture(Unfinished version)
![BottomMenuAndFullScreenDialogDarkModeSupport](https://user-images.githubusercontent.com/10115359/69497085-f9ebd900-0f13-11ea-9fd7-08690b09fa48.jpg)

**Comment by taksumaki** [comment]
It looks super good, but can you put custom colors too?

**Comment by kongzue** [comment]
I am trying to support.
At present, FullScreenDialog has been supported. BottomMenu and ShareDialog are not sure whether they can do it or not, because it involves dyeing problems of many components.

**Comment by kongzue** [comment]
You can upgrade to the beta version of 3.1.6.1 to try these new features.

**Comment by taksumaki** [comment]
Thanks you. :)
