### ISSUE TITLE
空指针异常

### ISSUE THREAD

**Issue by Andy957** [kongzue/DialogV3#98]
Attempt to invoke virtual method 'void com.kongzue.dialog.util.DialogHelper.dismiss()' on a null object reference

com.kongzue.dialog.util.BaseDialog.doDismiss(BaseDialog.java:241)

**Comment by kongzue** [comment]
如果你正在使用Support版本请更新至内测版本3.1.6.3，如果你正在使用AndroidX，请等待正式版更新

**Comment by Andy957** [comment]
ok，谢谢大佬
